'use client';
import { useState } from 'react';
import type { PosSnapshot, Station } from '@qatu/contracts';
import { stationName, printState, type CommandInput } from '../lib/client';
import { productionQueue, elapsedMinutes } from '../lib/operations';
export default function ProductionPanel({ snapshot, station, onStation, disabled, onAction }: { snapshot: PosSnapshot; station: Station; onStation?: (s: Station) => void; disabled: boolean; onAction: (c: CommandInput, message: string) => Promise<unknown> }) {
  const [reasons, setReasons] = useState<Record<string, string>>({});
  const queue = productionQueue(snapshot, station), kitchen = snapshot.user.role === 'kitchen', admin = snapshot.user.role === 'admin';
  const tableLabel = (visitId: string) => snapshot.tables.find(t => t.id === snapshot.visits.find(v => v.id === visitId)?.table_id)?.label ?? 'Mesa histórica';
  const canPriority = !kitchen && (admin || snapshot.user.role === 'waiter');
  return <>
    <div className="section-toolbar"><p className="muted">{station === 'caja' ? 'Entrega directa de bebidas · sin ticket de preparación.' : 'Orden por llegada. Una urgencia queda identificada con motivo; impresión, preparación y entrega son independientes.'}</p>{onStation && <div className="segmented">{(['cocina', 'heladeria'] as const).map(s => <button type="button" key={s} className={station === s ? 'selected' : ''} onClick={() => onStation(s)}>{stationName[s]}</button>)}</div>}</div>
    <div className="summary-grid"><div className="metric"><span>Tandas pendientes</span><strong>{queue.length}</strong></div><div className="metric"><span>Listos para llevar</span><strong>{queue.reduce((sum, o) => sum + o.lines.filter(l => l.station === station).reduce((n, l) => n + Math.max(0, (station === 'caja' ? l.quantity - (l.voided_quantity ?? 0) : l.prepared_quantity) - l.fulfilled_quantity), 0), 0)}</strong></div></div>
    <div className="fulfillment-grid">{queue.map((order, index) => <section className="panel fulfillment-card" key={order.id} aria-label={`Preparación ${tableLabel(order.visit_id)} tanda ${order.batch_number}`}>
      <div className="panel-heading"><div><span className="eyebrow">{index + 1} EN COLA · SECUENCIA {order.service_sequence ?? snapshot.orders.indexOf(order) + 1}</span><h2>{tableLabel(order.visit_id)}</h2><span className="muted small">Tanda {order.batch_number} · {elapsedMinutes(snapshot.server_time, order.created_at)} min desde registro · {order.responsible_name ?? 'Responsable por asignar'} · {order.source === 'guest' ? 'Cliente QR' : 'Personal'}</span></div><span className={`badge ${order.priority === 'urgent' ? 'amber' : 'teal'}`}>{order.priority === 'urgent' ? 'Urgente' : 'Por llegada'}</span></div>
      {order.priority_reason && <p className="line-note">Prioridad: {order.priority_reason}</p>}
      {order.lines.filter(l => l.station === station && l.quantity - (l.voided_quantity ?? 0) > l.fulfilled_quantity).map(line => {
        const active = line.quantity - (line.voided_quantity ?? 0), pending = active - line.fulfilled_quantity;
        const ready = (station === 'caja' ? active : line.prepared_quantity) - line.fulfilled_quantity;
        const mine = line.dispatch_claim?.actor_id === snapshot.user.id;
        return <div className="fulfillment-line" key={line.id}><div><strong>{line.product_name}</strong>{line.note && <p className="line-note">{line.note}</p>}<p className="small muted">{pending} pendientes · {line.fulfilled_quantity} entregados{station !== 'caja' ? ` · ${line.prepared_quantity} preparados · ${ready} listos` : ''}</p>{line.voided_quantity > 0 && <span className="badge danger">Anulado: {line.voided_quantity} u.</span>}{line.dispatch_claim && <p className="alert info small">Retiro reservado por {line.dispatch_claim.actor_name}: {line.dispatch_claim.quantity} u.</p>}</div><div className="line-actions">
          {station !== 'caja' && line.prepared_quantity < active && (kitchen || admin) && <button className="secondary" disabled={disabled} onClick={() => void onAction({ type: 'line.prepare', line_id: line.id, expected_version: line.version, quantity: 1 }, 'Una unidad registrada como preparada.')}>Preparar 1</button>}
          {station !== 'caja' && line.prepared_quantity < active && !kitchen && <details><summary>La estación confirmó que está listo</summary><label className="field"><span>Confirmación de {stationName[station]}</span><input minLength={3} maxLength={500} value={reasons[`ready:${line.id}`] ?? ''} onChange={e => setReasons(old => ({ ...old, [`ready:${line.id}`]: e.target.value }))} placeholder="Ej.: cocinero confirmó salida de un plato" /></label><button className="secondary" disabled={disabled || (reasons[`ready:${line.id}`]?.trim().length ?? 0) < 3} onClick={() => void onAction({ type: 'line.ready.confirm', line_id: line.id, expected_version: line.version, quantity: 1, reason: reasons[`ready:${line.id}`]!.trim() }, 'Confirmación de la estación registrada. Ahora puedes coordinar el retiro.')}>Registrar 1 confirmado listo</button></details>}
          {!kitchen && ready > 0 && !line.dispatch_claim && <button className="secondary" disabled={disabled} onClick={() => void onAction({ type: 'line.claim', line_id: line.id, expected_version: line.version, action: 'claim', quantity: 1, reason: 'Retiro coordinado desde terminal o tablet' }, 'Retiro reservado a tu nombre. Confirma la entrega después de llevarlo.')}>Reservar retiro de 1</button>}
          {line.dispatch_claim && (mine || admin) && <button className="secondary" disabled={disabled} onClick={() => void onAction({ type: 'line.claim', line_id: line.id, expected_version: line.version, action: 'release', reason: 'Liberación explícita de retiro desde salón' }, 'Retiro liberado. Otro compañero puede hacerse cargo.')}>Liberar retiro</button>}
          <button className="primary" disabled={disabled || ready <= 0 || (!!line.dispatch_claim && !mine) || (station !== 'caja' && !kitchen && !admin && !line.dispatch_claim)} onClick={() => void onAction({ type: 'line.fulfill', line_id: line.id, expected_version: line.version, quantity: 1 }, 'Entrega registrada. Stock actualizado una sola vez.')}>Entregar 1</button>
        </div></div>;
      })}
      {canPriority && station !== 'caja' && order.lines.some(l => l.station !== 'caja' && l.prepared_quantity < l.quantity - (l.voided_quantity ?? 0)) && <details><summary>Prioridad excepcional</summary><label className="field"><span>Motivo de prioridad</span><input minLength={3} maxLength={500} value={reasons[order.id] ?? ''} onChange={e => setReasons(old => ({ ...old, [order.id]: e.target.value }))} /></label><button className="secondary" disabled={disabled || (reasons[order.id]?.trim().length ?? 0) < 3} onClick={() => void onAction({ type: 'order.priority', order_id: order.id, expected_version: order.production_version ?? 1, priority: order.priority === 'urgent' ? 'normal' : 'urgent', reason: reasons[order.id]!.trim() }, 'Prioridad actualizada y aviso registrado. No se repitió el pedido.')}>{order.priority === 'urgent' ? 'Volver a orden de llegada' : 'Marcar urgente con motivo'}</button></details>}
      {station !== 'caja' && snapshot.print_jobs.filter(j => j.order_id === order.id && j.station === station).map(job => <div className="print-job" key={job.id}><div><span>▤ {job.copy_of ? 'Copia rotulada' : job.kind === 'priority' ? 'AVISO DE PRIORIDAD · NO REPETIR PEDIDO' : job.kind === 'void' || job.reason?.includes('ANULACIÓN') ? 'TICKET DE ANULACIÓN' : 'Ticket original'}</span><strong>{printState[job.state]}</strong></div><p className="small muted">{job.table_label ?? tableLabel(order.visit_id)} · tanda {job.batch_number ?? order.batch_number} · secuencia {job.service_sequence ?? order.service_sequence} · {job.responsible_name ?? order.responsible_name}</p>{job.reason && <p className="line-note">{job.reason}</p>}<details><summary>Opciones del ticket</summary><label className="field"><span>Motivo de copia</span><input value={reasons[job.id] ?? ''} onChange={e => setReasons(old => ({ ...old, [job.id]: e.target.value }))} /></label><button className="secondary" disabled={disabled || (reasons[job.id]?.trim().length ?? 0) < 3} onClick={() => void onAction({ type: 'print.copy', print_job_id: job.id, expected_version: job.version, reason: reasons[job.id]! }, 'Copia rotulada creada. No se repitió el pedido.')}>Crear copia rotulada</button>{snapshot.environment === 'laboratory' ? <><p className="small muted">Simulador de impresión · sin conexión a hardware</p><div className="button-row">{(['confirmed', 'failed_before_send', 'ambiguous'] as const).map(state => <button className="text-button" key={state} disabled={disabled} onClick={() => void onAction({ type: 'print.ack', print_job_id: job.id, expected_version: job.version, state, evidence: 'Simulador de laboratorio desde terminal staff' }, 'Estado de impresión simulado actualizado.')}>{state === 'confirmed' ? 'Simular confirmación' : state === 'ambiguous' ? 'Simular incierto' : 'Simular fallo'}</button>)}</div></> : <p className="small muted">Puente de impresión de red pendiente. No se confirma impresión desde esta pantalla.</p>}</details></div>)}
    </section>)}</div>
    {!queue.length && <section className="panel"><h2>{station === 'caja' ? 'Bebidas al día' : 'Estación al día'}</h2><p className="muted">Las nuevas tandas aparecerán aquí cuando se registren.</p></section>}
  </>;
}
