'use client';
import { useState } from 'react';
import type { CommandResponse, PosSnapshot, StaffRole, StaffUser, Station } from '@qatu/contracts';
import { type CommandInput, roleName } from '../lib/client';
import { setStaffPassword } from '../lib/staff-client';
const defaults = { username: '', name: '', role: 'waiter' as StaffRole, station: null as Station | null, reason: '' };
function stationFor(role: StaffRole): Station | null { return role === 'cashier' ? 'caja' : role === 'kitchen' ? 'cocina' : null; }
export default function StaffPanel({ snapshot, csrf, disabled, onAction, onRefresh }: { snapshot: PosSnapshot; csrf: string; disabled: boolean; onAction: (input: CommandInput, notice: string) => Promise<CommandResponse | null>; onRefresh: () => Promise<void> }) {
  const [create, setCreate] = useState(defaults), [edit, setEdit] = useState<StaffUser | null>(null), [editReason, setEditReason] = useState(''), [accessReason, setAccessReason] = useState('');
  const [credential, setCredential] = useState<{ id: string; name: string; version: number } | null>(null), [currentPassword, setCurrentPassword] = useState(''), [newPassword, setNewPassword] = useState(''), [credentialReason, setCredentialReason] = useState(''), [credentialBusy, setCredentialBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  if (snapshot.user.role !== 'admin') return null;
  const blocked = disabled || credentialBusy;
  function chooseCredential(s: StaffUser) { setCredential({ id: s.id, name: s.name, version: s.version ?? 1 }); setCurrentPassword(''); setNewPassword(''); setCredentialReason(''); setError(''); setNotice(''); }
  async function saveCredential(e: React.FormEvent) { e.preventDefault(); if (!credential || blocked) return; setCredentialBusy(true); setError(''); setNotice('');
    try { await setStaffPassword(credential.id, { expected_version: credential.version, current_password: currentPassword, new_password: newPassword, reason: credentialReason }, csrf); setCurrentPassword(''); setNewPassword(''); setCredential(null); setNotice('Contraseña individual establecida; las sesiones anteriores se revocaron. Activa la persona si todavía está inactiva.'); await onRefresh(); }
    catch (e) { setError(e instanceof Error ? e.message : 'No se pudo establecer la credencial.'); await onRefresh(); }
    finally { setCredentialBusy(false); }
  }
  return <>
    <section className="panel"><span className="eyebrow">IDENTIDADES INDIVIDUALES</span><h2>Equipo del restaurante</h2><p className="muted">Cada mozo y cajero entra con su propia cuenta. Dos pantallas compartidas no comparten firma. No se desactiva a quien conserva mesas, retiros o custodia sin resolver.</p>{notice && <div className="alert info" role="status">{notice}</div>}{error && <div className="alert error" role="alert">{error}</div>}
      <label className="field"><span>Motivo de cambio de acceso</span><input maxLength={500} value={accessReason} onChange={e => setAccessReason(e.target.value)} placeholder="Alta operativa, pausa o relevo verificado" /></label>
      <div className="table-scroll"><table><thead><tr><th>Persona</th><th>Perfil</th><th>Acceso</th><th>Acciones</th></tr></thead><tbody>{snapshot.staff.map(s => <tr key={s.id}><td><strong>{s.name}</strong><br /><span className="small muted">{s.username} · versión {s.version ?? 1}</span></td><td>{roleName[s.role]}{s.station && ` · ${s.station}`}</td><td>{s.active === false ? 'Inactivo' : 'Activo'}<br /><span className="small muted">{s.credential_ready === false ? 'Contraseña pendiente' : 'Credencial establecida'}</span></td><td><div className="button-row"><button className="text-button" disabled={blocked} onClick={() => { setEdit({ ...s, version: s.version ?? 1, active: s.active !== false }); setEditReason(''); }}>Editar {s.name}</button><button className="text-button" disabled={blocked} onClick={() => chooseCredential(s)}>Credencial {s.name}</button><button className="secondary" disabled={blocked || accessReason.trim().length < 3 || s.id === snapshot.user.id || s.active === false && s.credential_ready === false} onClick={() => void onAction({ type: 'staff.update', staff_id: s.id, expected_version: s.version ?? 1, name: s.name, role: s.role, station: s.station, active: s.active === false, reason: accessReason }, s.active === false ? 'Persona activada con identidad individual.' : 'Persona desactivada; sus sesiones se revocaron.')}>{s.active === false ? 'Activar' : 'Desactivar'} {s.name}</button></div></td></tr>)}</tbody></table></div>
    </section>
    {credential && <section className="panel narrow-panel"><h2>Credencial de {credential.name}</h2><p className="muted">Confirma tu contraseña administrativa y establece la nueva. No se guarda en el historial ni en los borradores. Se invalidan las sesiones anteriores de esta persona.</p><form className="form-stack" onSubmit={e => void saveCredential(e)}><label className="field"><span>Tu contraseña administrativa actual</span><input type="password" autoComplete="current-password" maxLength={128} value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required /></label><label className="field"><span>Nueva contraseña individual</span><input type="password" autoComplete="new-password" minLength={12} maxLength={128} value={newPassword} onChange={e => setNewPassword(e.target.value)} required /></label><label className="field"><span>Motivo de credencial</span><input minLength={3} maxLength={500} value={credentialReason} onChange={e => setCredentialReason(e.target.value)} required /></label><button className="primary" disabled={blocked}>Establecer contraseña individual</button><button type="button" className="secondary" disabled={blocked} onClick={() => { setCredential(null); setCurrentPassword(''); setNewPassword(''); }}>Cancelar credencial</button></form></section>}
    {edit && <section className="panel narrow-panel"><h2>Editar perfil de {edit.username}</h2><form className="form-stack" onSubmit={e => { e.preventDefault(); void onAction({ type: 'staff.update', staff_id: edit.id, expected_version: edit.version ?? 1, name: edit.name, role: edit.role, station: edit.station, active: edit.active !== false, reason: editReason }, 'Perfil actualizado; las sesiones anteriores se revocaron.').then(r => { if (r) setEdit(null); }); }}><label className="field"><span>Nombre de la persona</span><input minLength={2} maxLength={100} value={edit.name} onChange={e => setEdit({ ...edit, name: e.target.value })} required /></label><label className="field"><span>Perfil de la persona</span><select value={edit.role} onChange={e => { const role = e.target.value as StaffRole; setEdit({ ...edit, role, station: stationFor(role) }); }}>{Object.entries(roleName).map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select></label>{edit.role === 'kitchen' && <label className="field"><span>Estación de la persona</span><select value={edit.station ?? 'cocina'} onChange={e => setEdit({ ...edit, station: e.target.value as Station })}><option value="cocina">Cocina</option><option value="heladeria">Heladería</option></select></label>}<label className="field"><span>Motivo de edición del perfil</span><input minLength={3} maxLength={500} value={editReason} onChange={e => setEditReason(e.target.value)} required /></label><button className="primary" disabled={blocked}>Guardar perfil individual</button><button type="button" className="secondary" disabled={blocked} onClick={() => setEdit(null)}>Cancelar edición</button></form></section>}
    <section className="panel narrow-panel"><h2>Crear una persona</h2><p className="muted">Primero crea el perfil; después establece su contraseña y activa su acceso. Nunca se asigna la clave de demostración.</p><form className="form-stack" onSubmit={e => { e.preventDefault(); void onAction({ type: 'staff.create', ...create }, 'Perfil creado inactivo. Establece su contraseña individual antes de activarlo.').then(r => { if (r) setCreate(defaults); }); }}><label className="field"><span>Usuario individual</span><input pattern="[a-z][a-z0-9_.-]{2,49}" minLength={3} maxLength={50} autoComplete="off" value={create.username} onChange={e => setCreate({ ...create, username: e.target.value.toLowerCase() })} required /></label><label className="field"><span>Nombre visible</span><input minLength={2} maxLength={100} value={create.name} onChange={e => setCreate({ ...create, name: e.target.value })} required /></label><label className="field"><span>Perfil inicial</span><select value={create.role} onChange={e => { const role = e.target.value as StaffRole; setCreate({ ...create, role, station: stationFor(role) }); }}>{Object.entries(roleName).map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select></label>{create.role === 'kitchen' && <label className="field"><span>Estación inicial</span><select value={create.station ?? 'cocina'} onChange={e => setCreate({ ...create, station: e.target.value as Station })}><option value="cocina">Cocina</option><option value="heladeria">Heladería</option></select></label>}<label className="field"><span>Motivo de alta</span><input minLength={3} maxLength={500} value={create.reason} onChange={e => setCreate({ ...create, reason: e.target.value })} required /></label><button className="primary" disabled={blocked}>Crear perfil individual</button></form></section>
  </>;
}
