'use client';
import { useState } from 'react';
import type { PosSnapshot } from '@qatu/contracts';
import { type CommandInput, parseQuantity } from '../lib/client';
export default function StockSupplyPanel({ snapshot, disabled, onAction }: { snapshot: PosSnapshot; disabled: boolean; onAction: (input: CommandInput, message: string) => Promise<unknown> }) {
  const admin = snapshot.user.role === 'admin';
  const [create, setCreate] = useState({ name: '', sku: '', station: 'caja' as 'caja' | 'heladeria', beverage_kind: 'water' as 'water' | 'beer' | 'soda' | null, reason: '' });
  const [receive, setReceive] = useState({ stock_item_id: '', expected_version: 0, quantity: '', receipt_reference: '', reason: '' }), [error, setError] = useState('');
  const stock = snapshot.stock.filter(s => admin || s.station === 'caja');
  const changed = !!receive.stock_item_id && snapshot.stock.find(s => s.id === receive.stock_item_id)?.version !== receive.expected_version;
  return <section className="panel"><h2>Ingreso de mercadería</h2><p className="muted">Registra unidades físicas recibidas con referencia de proveedor/documento. No genera una venta, un gasto de caja ni confirma una factura de compra.</p>{error && <div className="alert error" role="alert">{error}</div>}
    <form className="form-stack" onSubmit={e => { e.preventDefault(); setError(''); try { if (changed) throw new Error('Cambió el inventario. Selecciona nuevamente el producto y verifica las unidades antes de recibir.'); void onAction({ type: 'stock.receive', stock_item_id: receive.stock_item_id, expected_version: receive.expected_version, quantity: parseQuantity(receive.quantity), receipt_reference: receive.receipt_reference, reason: receive.reason }, 'Recepción física registrada una vez; dinero y ventas conservan su estado.').then(r => { if (r) setReceive({ stock_item_id: '', expected_version: 0, quantity: '', receipt_reference: '', reason: '' }); }); } catch (err) { setError(err instanceof Error ? err.message : 'Verifica la recepción.'); } }}><label className="field"><span>Producto recibido</span><select value={receive.stock_item_id} onChange={e => { const s = stock.find(s => s.id === e.target.value); setReceive({ ...receive, stock_item_id: s?.id ?? '', expected_version: s?.version ?? 0 }); }} required><option value="">Selecciona un SKU</option>{stock.map(s => <option key={s.id} value={s.id}>{s.sku} · {s.name}</option>)}</select></label><label className="field"><span>Unidades recibidas</span><input inputMode="numeric" pattern="[0-9]{1,5}" value={receive.quantity} onChange={e => setReceive({ ...receive, quantity: e.target.value })} required /></label><label className="field"><span>Referencia de recepción</span><input minLength={3} maxLength={100} value={receive.receipt_reference} onChange={e => setReceive({ ...receive, receipt_reference: e.target.value })} placeholder="Proveedor y documento, por ejemplo PROVEEDOR/F001-123" required /></label><label className="field"><span>Motivo de recepción</span><input minLength={3} maxLength={500} value={receive.reason} onChange={e => setReceive({ ...receive, reason: e.target.value })} required /></label>{changed && <p className="alert info">Cambió la versión del inventario: revisa y vuelve a seleccionar el SKU.</p>}<button className="primary" disabled={disabled || changed || !receive.stock_item_id || snapshot.business_day.state !== 'open'}>Registrar recepción física</button></form>
    {admin && <details><summary>Crear SKU de inventario</summary><p className="muted">Se crea con cero existencias. Después registra la recepción y enlázalo al producto/precio desde Carta.</p><form className="form-stack" onSubmit={e => { e.preventDefault(); void onAction({ type: 'stock.create', ...create }, 'SKU creado con cero existencias; recibe sus unidades antes de vender.').then(r => { if (r) setCreate({ name: '', sku: '', station: 'caja', beverage_kind: 'water', reason: '' }); }); }}><label className="field"><span>Nombre del SKU</span><input minLength={2} maxLength={100} value={create.name} onChange={e => setCreate({ ...create, name: e.target.value })} required /></label><label className="field"><span>Código SKU</span><input pattern="[A-Z0-9][A-Z0-9_-]{1,49}" value={create.sku} onChange={e => setCreate({ ...create, sku: e.target.value.toUpperCase() })} required /></label><label className="field"><span>Estación del SKU</span><select value={create.station} onChange={e => { const station = e.target.value as 'caja' | 'heladeria'; setCreate({ ...create, station, beverage_kind: station === 'caja' ? 'water' : null }); }}><option value="caja">Caja</option><option value="heladeria">Heladería</option></select></label>{create.station === 'caja' && <label className="field"><span>Clase de bebida</span><select value={create.beverage_kind ?? 'water'} onChange={e => setCreate({ ...create, beverage_kind: e.target.value as 'water' | 'beer' | 'soda' })}><option value="water">Agua</option><option value="beer">Cerveza</option><option value="soda">Gaseosa</option></select></label>}<label className="field"><span>Motivo de alta de SKU</span><input minLength={3} maxLength={500} value={create.reason} onChange={e => setCreate({ ...create, reason: e.target.value })} required /></label><button className="secondary" disabled={disabled || snapshot.business_day.state !== 'open'}>Crear SKU con stock cero</button></form></details>}
  </section>;
}
