import { test, expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

async function signIn(page:Page,user:string) {
  await page.goto('/');await page.getByLabel('Usuario',{exact:true}).fill(user);
  await page.getByLabel('Contraseña',{exact:true}).fill('QatuDemo2026!');
  await page.getByRole('button',{name:'Ingresar a mi espacio'}).click();
  await expect(page.getByRole('navigation',{name:'Secciones de operación'})).toBeVisible();
}
test('two touch terminals share a mixed table order and cashier records exact cash change',async({browser})=>{
  const waiterContext=await browser.newContext(),secondContext=await browser.newContext(),cashContext=await browser.newContext();
  const waiter=await waiterContext.newPage(),second=await secondContext.newPage(),cashier=await cashContext.newPage();
  await signIn(cashier,'caja');await cashier.getByRole('button',{name:'Mi turno'}).click();
  await cashier.getByLabel('Fondo físico inicial (S/)').fill('200.00');await cashier.getByRole('button',{name:'Abrir mi sesión'}).click();
  await expect(cashier.getByRole('status')).toContainText('Sesión de caja abierta');
  await signIn(waiter,'mozo');
  // Independent terminal must not inherit another browser context's staff cookie.
  expect((await secondContext.cookies()).some(c => c.name === 'qatu_session')).toBe(false);
  expect((await secondContext.request.get('/v1/pos/session')).status()).toBe(401);
  await signIn(second,'mozo');
  await waiter.getByRole('button',{name:/Mesa 01/}).click();
  await waiter.getByRole('button',{name:/Ceviche clásico/}).click();
  await waiter.getByRole('button',{name:/Cerveza personal/}).click();
  await waiter.getByRole('button',{name:/Refresco de maracuyá/}).click();
  await waiter.getByLabel('Observación para Ceviche clásico').fill('Sin picante');
  await waiter.getByRole('button',{name:'Enviar pedido'}).click();
  await waiter.getByRole('dialog').getByRole('button',{name:'Enviar 3 productos'}).click();
  await expect(waiter.locator('.current-account')).toContainText('53.00');
  await expect(second.getByRole('button',{name:/Mesa 01/})).toContainText('53.00');
  await second.getByRole('button',{name:/Mesa 01/}).click();
  await expect(second.locator('.current-account')).toContainText('53.00');
  await waiter.getByRole('navigation').getByRole('button',{name:/Bebidas/}).click();await waiter.getByRole('button',{name:'Entregar 1',exact:true}).click();
  await expect(waiter.getByRole('status')).toContainText('Entrega registrada');
  await cashier.getByRole('button',{name:'Caja',exact:false}).first().click();
  await cashier.locator('.check-row').filter({hasText:'Mesa 01'}).click();
  await cashier.getByLabel('Importe a cobrar (S/)').fill('53.00');
  await cashier.getByRole('button',{name:/Reservar/}).click();
  await cashier.getByLabel('Efectivo recibido (S/)').fill('60.00');
  await cashier.getByRole('button',{name:'Confirmar efectivo y cambio'}).click();
  await expect(cashier.getByRole('status')).toContainText('Cobro registrado');
  await expect(cashier.locator('.check-row').filter({hasText:'Mesa 01'})).toContainText('0.00');
  await mkdir('docs/evidence/screens',{recursive:true});
  await cashier.screenshot({path:'docs/evidence/screens/caja.png',fullPage:true});
  const kitchenContext=await browser.newContext(),kitchen=await kitchenContext.newPage();await signIn(kitchen,'cocina');
  await expect(kitchen.getByRole('navigation')).not.toContainText('Mi turno');
  await expect(kitchen.locator('.fulfillment-card').first()).toContainText('Sin picante');
  await kitchen.getByRole('button',{name:'Preparar 1',exact:true}).click();
  await expect(kitchen.getByRole('status')).toContainText('preparada');
  await kitchen.screenshot({path:'docs/evidence/screens/cocina.png',fullPage:true});
  await kitchen.getByRole('button',{name:'Entregar 1',exact:true}).click();
  const iceContext=await browser.newContext(),ice=await iceContext.newPage();await signIn(ice,'heladeria');
  await ice.getByRole('button',{name:'Preparar 1',exact:true}).click();await ice.getByRole('button',{name:'Entregar 1',exact:true}).click();
  await cashier.getByRole('button',{name:'Mi turno'}).click();
  await cashier.getByLabel('Recibe el turno').selectOption('10000000-0000-4000-8000-000000000003');
  await cashier.getByRole('button',{name:'Preparar corte y comenzar conteo'}).click();
  await expect(cashier.getByText('Los esperados permanecen ocultos hasta guardar.',{exact:false})).toBeVisible();
  await cashier.getByLabel('Efectivo contado (S/)').fill('253.00');
  await cashier.getByLabel('Cerveza personal · unidades físicas').fill('47');
  await cashier.getByLabel('Gaseosa personal · unidades físicas').fill('36');
  await cashier.getByLabel('Agua · unidades físicas').fill('24');
  await cashier.getByRole('button',{name:'Guardar declaración de conteo'}).click();
  const nightContext=await browser.newContext(),night=await nightContext.newPage();await signIn(night,'noche');await night.getByRole('button',{name:'Mi turno'}).click();
  await night.getByRole('button',{name:'Confirmar recepción de caja y bebidas'}).click();
  await expect(night.getByRole('status')).toContainText('Traspaso aceptado');
  await night.getByRole('button',{name:'Cierre del día'}).click();
  await night.getByLabel('Efectivo final contado (S/)').fill('253.00');
  await night.getByLabel('Cerveza personal · unidades físicas').fill('47');
  await night.getByLabel('Gaseosa personal · unidades físicas').fill('36');
  await night.getByLabel('Agua · unidades físicas').fill('24');
  await night.getByLabel('Observaciones del cierre').fill('Conteo completo al fin de jornada');
  await night.getByRole('button',{name:'Revisar y guardar cierre'}).click();
  await night.getByRole('dialog').getByRole('button',{name:'Confirmar cierre provisional'}).click();
  await expect(night.getByRole('heading',{name:'Resultado del día'})).toBeVisible();
  await expect(night.locator('.summary-grid').first()).toContainText('53.00');
  await night.screenshot({path:'docs/evidence/screens/cierre.png',fullPage:true});
  const adminContext=await browser.newContext(),admin=await adminContext.newPage();await signIn(admin,'admin');
  await admin.getByRole('button',{name:'Cierre del día'}).click();
  await admin.getByLabel('Motivo de apertura del siguiente día').fill('Ensayar recuperación del siguiente día');
  await admin.getByRole('button',{name:'Comenzar siguiente día de prueba'}).click();
  await expect(admin.getByRole('status')).toContainText('Nuevo día operativo');
  await cashier.getByRole('button',{name:'Mi turno'}).click();
  await cashier.getByLabel('Fondo físico inicial (S/)').fill('0.00');await cashier.getByRole('button',{name:'Abrir mi sesión'}).click();
  await waiter.getByRole('navigation').getByRole('button',{name:/Mesas/}).click();
  await waiter.getByRole('button',{name:/Volver a mesas/}).click();
  await waiter.getByRole('button',{name:/Mesa 02/}).click();await waiter.getByRole('button',{name:/Ceviche clásico/}).click();
  let loseResponse=true;
  await waiter.route('**/v1/pos/commands',async route=>{
    if(route.request().postDataJSON()?.type==='order.create' && loseResponse) {
      loseResponse=false;await route.fetch();await route.abort('failed');
    } else await route.continue();
  });
  await waiter.getByRole('button',{name:'Enviar pedido'}).click();
  await waiter.getByRole('dialog').getByRole('button',{name:'Enviar 1 productos'}).click();
  await expect(waiter.getByText('Respuesta pendiente de confirmación')).toBeVisible();
  await waiter.reload();await expect(waiter.getByText('Respuesta pendiente de confirmación')).toBeVisible();
  await waiter.getByRole('button',{name:'Consultar y recuperar'}).click();
  await expect(waiter.getByRole('status')).toContainText('Operación recuperada');
  await waiter.getByRole('button',{name:/Mesa 02/}).click();
  await expect(waiter.locator('.current-account')).toContainText('35.00');
  await expect(waiter.locator('.draft-lines')).toContainText('Empecemos el pedido');
  await waiter.locator('.previous-orders summary').click();await expect(waiter.locator('.history-batch')).toHaveCount(1);
  await waiter.screenshot({path:'docs/evidence/screens/pedido.png',fullPage:true});
  await cashier.getByRole('navigation').getByRole('button',{name:/Caja/}).click();
  await cashier.locator('.check-row').filter({hasText:'Mesa 02'}).click();
  await cashier.getByRole('button',{name:'Yape',exact:true}).click();await cashier.getByRole('button',{name:/Reservar importe/}).click();
  await expect(cashier.getByLabel('Cuenta o terminal del comercio')).toHaveValue('comercio-laboratorio');
  await cashier.getByRole('button',{name:'No puedo confirmar el resultado'}).click();
  await cashier.getByRole('dialog').getByRole('button',{name:'Registrar como incierto'}).click();
  await expect(cashier.locator('.pending-payment')).toContainText('35.00');
  await cashier.getByLabel('Referencia confirmada').fill('YAPE-E2E-SINTETICO-02');
  await cashier.getByRole('button',{name:'Resolver con evidencia'}).click();
  await expect(cashier.getByRole('status')).toContainText('Pago incierto resuelto');
  await expect(cashier.locator('.pending-payment')).toHaveCount(0);
  for(const context of [waiterContext,secondContext,cashContext,kitchenContext,iceContext,nightContext,adminContext])await context.close();
});
test('mobile layout stays inside the viewport with accessible table controls',async({browser})=>{
  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await signIn(mobile,'mozo');
  await expect(mobile.getByRole('button',{name:/Mesa 02/})).toBeVisible();
  expect(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await mobile.screenshot({path:'docs/evidence/screens/mobile.png',fullPage:true});await mobileContext.close();
});
