import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('Carta guides compatible stock selection, audits route before first sale', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Usuario', { exact: true }).fill('admin');
  await page.getByLabel('Contraseña', { exact: true }).fill('QatuDemo2026!');
  await page.getByRole('button', { name: 'Ingresar a mi espacio' }).click();
  await expect(page.getByRole('navigation', { name: 'Secciones de operación' })).toBeVisible();
  await page.getByRole('navigation').getByRole('button', { name: /Carta/ }).click();
  await page.getByRole('button', { name: '+ Nuevo producto' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre del producto').fill('Oferta E2E custodia');
  await dialog.getByLabel('Categoría', { exact: true }).fill('Laboratorio');
  await dialog.getByLabel('Precio (S/)').fill('12.00');
  await dialog.getByLabel('Motivo del alta').fill('Ensayo de catálogo por estación');
  await dialog.getByLabel('Política de stock').selectOption('unit');
  await expect(dialog.getByRole('status')).toContainText('No hay inventario por unidad');
  await expect(dialog.getByRole('button', { name: 'Crear producto' })).toBeDisabled();
  await dialog.getByLabel('Estación de atención').selectOption('caja');
  await expect(dialog).toContainText('entrega directa, sin ticket');
  const stock = dialog.getByLabel('Ítem de inventario vinculado');
  await expect(stock.locator('option')).toHaveCount(4);
  await expect(stock).toHaveValue('');
  await expect(dialog.getByRole('button', { name: 'Crear producto' })).toBeDisabled();
  await stock.selectOption({ label: 'Cerveza personal (BEB-CERV-330)' });
  await dialog.getByRole('button', { name: 'Crear producto' }).click();
  await expect(page.getByRole('status')).toContainText('Producto creado correctamente');
  const row = page.locator('tr').filter({ hasText: 'Oferta E2E custodia' });
  await expect(row).toContainText('Cerveza personal');
  await row.getByRole('button', { name: 'Editar' }).click();
  await expect(dialog.getByRole('heading', { name: 'Editar producto' })).toBeVisible();
  await dialog.getByLabel('Estación').selectOption('heladeria');
  await expect(dialog.getByLabel('Ítem de inventario vinculado')).toHaveValue('');
  await expect(dialog.getByRole('button', { name: 'Guardar cambios' })).toBeDisabled();
  await expect(dialog.getByLabel('Ítem de inventario vinculado').locator('option')).toHaveCount(2);
  await dialog.getByLabel('Ítem de inventario vinculado').selectOption({ label: 'Helado individual (HEL-IND)' });
  await dialog.getByLabel('Motivo de la modificación').fill('Corrección de oferta antes de vender');
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('status')).toContainText('Producto actualizado');
  await expect(row).toContainText('Heladería'); await expect(row).toContainText('Helado individual');
  const audit = page.locator('details').filter({ hasText: 'Historial de auditoría de la carta' });
  await audit.locator('summary').click();
  await expect(audit).toContainText('Estación: Bebidas de Caja → Heladería');
  await expect(audit).toContainText('Inventario vinculado: Cerveza personal → Helado individual');
  await mkdir('docs/evidence/screens', { recursive: true });
  await page.screenshot({ path: 'docs/evidence/screens/catalogo-custodia-012.png', fullPage: true });
});
