import { test, expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
async function login(page:Page, username:string, password='QatuDemo2026!') { await page.goto('/'); await page.getByLabel('Usuario',{exact:true}).fill(username); await page.getByLabel('Contraseña',{exact:true}).fill(password); await page.getByRole('button',{name:'Ingresar a mi espacio'}).click(); await expect(page.getByRole('navigation',{name:'Secciones de operación'})).toBeVisible(); }
async function snapshot(page:Page) { return (await page.request.get('/v1/pos/snapshot')).json(); }
test('admin provisions individual tablet account and rotates credential without storing passwords in drafts',async({browser})=>{
  const adminContext=await browser.newContext(), staffContext=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true});const admin=await adminContext.newPage(),staff=await staffContext.newPage();
  try { await login(admin,'otro_admin'); await admin.getByRole('navigation').getByRole('button',{name:/Personal/}).click();
    await admin.getByLabel('Usuario individual',{exact:true}).fill('apoyo_tablet');await admin.getByLabel('Nombre visible',{exact:true}).fill('Apoyo Tablet');await admin.getByLabel('Motivo de alta',{exact:true}).fill('Nueva tablet con firma individual');await admin.getByRole('button',{name:'Crear perfil individual'}).click();
    const row=admin.getByRole('row').filter({hasText:'apoyo_tablet'});await expect(row).toContainText('Inactivo');await expect(row.getByRole('button',{name:'Activar Apoyo Tablet',exact:true})).toBeDisabled();
    await row.getByRole('button',{name:'Credencial Apoyo Tablet',exact:true}).click();await admin.getByLabel('Tu contraseña administrativa actual').fill('QatuDemo2026!');await admin.getByLabel('Nueva contraseña individual').fill('TabletIndividual2026!');await admin.getByLabel('Motivo de credencial').fill('Entrega de acceso individual');await admin.getByRole('button',{name:'Establecer contraseña individual'}).click();await expect(row).toContainText('Credencial establecida');
    await admin.getByLabel('Motivo de cambio de acceso').fill('Alta revisada de tablet');await row.getByRole('button',{name:'Activar Apoyo Tablet',exact:true}).click();await expect(row).toContainText('Activo');
    await login(staff,'apoyo_tablet','TabletIndividual2026!');await expect(staff.getByRole('navigation').getByRole('button',{name:/Personal/})).toHaveCount(0);
    await row.getByRole('button',{name:'Credencial Apoyo Tablet',exact:true}).click();await admin.getByLabel('Tu contraseña administrativa actual').fill('QatuDemo2026!');await admin.getByLabel('Nueva contraseña individual').fill('TabletRotada2026!');await admin.getByLabel('Motivo de credencial').fill('Rotación de credencial verificada');await admin.getByRole('button',{name:'Establecer contraseña individual'}).click();await expect(row).toContainText('versión 4');expect((await staff.request.get('/v1/pos/session')).status()).toBe(401);
    const storage=await admin.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));expect(storage).not.toContain('TabletIndividual2026!');expect(storage).not.toContain('TabletRotada2026!');
    await mkdir('docs/evidence/screens',{recursive:true});await admin.screenshot({path:'docs/evidence/screens/personal-015.png',fullPage:true});
  } finally { await adminContext.close();await staffContext.close(); }
});
test('physical receiving creates zero-stock SKU then increases stock without cash movement',async({page})=>{
  await login(page,'otro_admin');let before=await snapshot(page);if(before.business_day.state!=='open'){const session=await(await page.request.get('/v1/pos/session')).json();const r=await page.request.post('/v1/pos/commands',{headers:{'x-csrf-token':session.csrf_token},data:{operation_id:crypto.randomUUID(),type:'day.open',expected_day_version:before.business_day.version,reason:'Recepción física de prueba'}});expect(r.status()).toBe(200);await page.reload();}
  await page.getByRole('navigation').getByRole('button',{name:/Inventario/}).click();await page.getByText('Crear SKU de inventario',{exact:true}).click();await page.getByLabel('Nombre del SKU').fill('Agua recepción UI');await page.getByLabel('Código SKU').fill('AGUA-REC-UI');await page.getByLabel('Motivo de alta de SKU').fill('Nuevo envase para el restaurante');await page.getByRole('button',{name:'Crear SKU con stock cero'}).click();await expect(page.locator('div.alert[role="status"]')).toContainText('SKU creado');before=await snapshot(page);const sku=before.stock.find((s:any)=>s.sku==='AGUA-REC-UI');expect(sku.on_hand).toBe(0);
  await page.getByLabel('Producto recibido').selectOption(sku.id);await page.getByLabel('Unidades recibidas').fill('12');await page.getByLabel('Referencia de recepción').fill('PROV/GUIA-UI-001');await page.getByLabel('Motivo de recepción').fill('Doce botellas recibidas y verificadas');await page.getByRole('button',{name:'Registrar recepción física'}).click();await expect(page.locator('div.alert[role="status"]')).toContainText('Recepción física registrada');const after=await snapshot(page);expect(after.stock.find((s:any)=>s.id===sku.id).on_hand).toBe(12);expect(after.cash_sessions).toEqual(before.cash_sessions);expect(after.payments).toEqual(before.payments);expect(after.checks).toEqual(before.checks);await page.screenshot({path:'docs/evidence/screens/recepcion-stock-015.png',fullPage:true});
});
