import { handleCloudRequest } from '@qatu/commerce/serverless';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=30;
export const GET=handleCloudRequest;
export const HEAD=handleCloudRequest;
export const POST=handleCloudRequest;
export const PUT=handleCloudRequest;
export const PATCH=handleCloudRequest;
export const DELETE=handleCloudRequest;
export const OPTIONS=handleCloudRequest;
