import {beforeAll,afterAll,beforeEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {createApp} from '../../services/commerce/src/app.js';
import {testDatabase} from '../support/database.js';
let db:Awaited<ReturnType<typeof testDatabase>>,app:Awaited<ReturnType<typeof createApp>>;
beforeAll(async()=>{db=await testDatabase();app=await createApp(db.pool,false);},30000);
beforeEach(async()=>{await db.reset();});
afterAll(async()=>{await app?.close();await db?.close();},30000);
async function login(name='mozo'){const r=await app.inject({method:'POST',url:'/v1/pos/session',payload:{username:name,password:'QatuDemo2026!'}});expect(r.statusCode).toBe(200);return {cookie:r.cookies[0]!.name+'='+r.cookies[0]!.value,csrf:r.json().csrf_token};}
async function send(w:any,payload:any){return app.inject({method:'POST',url:'/v1/pos/commands',headers:{cookie:w.cookie,'x-csrf-token':w.csrf},payload:{operation_id:randomUUID(),...payload}});}
async function setup(){const w=await login();const s=(await app.inject({url:'/v1/pos/snapshot',headers:{cookie:w.cookie}})).json();const opened=await send(w,{type:'table.open',table_id:s.tables[0].id,expected_version:1});expect(opened.statusCode).toBe(200);const v=opened.json().snapshot.visits[0];const q=await app.inject({method:'POST',url:'/v1/pos/quotes',headers:{cookie:w.cookie},payload:{visit_id:v.id,lines:[{product_id:s.products[0].id,quantity:1}]}});expect(q.statusCode).toBe(200);return {w,v,q:q.json()};}
describe('corrective011 PostgreSQL boundary',()=>{
 it('same operation recovers once; consumed quote with new intent rejects atomically',async()=>{const {w,v,q}=await setup(),body={type:'order.create',operation_id:randomUUID(),visit_id:v.id,expected_version:1,quote_id:q.quote_id};const a=await send(w,body);expect(a.statusCode,a.body).toBe(200);const replay=await send(w,body);expect(replay.statusCode).toBe(200);expect(replay.json().replayed).toBe(true);const reused=await send(w,{...body,operation_id:randomUUID(),expected_version:a.json().snapshot.visits[0].version});expect(reused.statusCode).toBe(409);expect(reused.json().error.code).toBe('INVALID_TRANSITION');const state=(await app.inject({url:'/v1/pos/snapshot',headers:{cookie:w.cookie}})).json();expect(state.orders).toHaveLength(1);expect(state.checks[0].total_minor).toBe(3500);expect(Number((await db.pool.query("SELECT count(*) FROM outbox WHERE type='order.create'")).rows[0].count)).toBe(1);});
 it('quote cannot be accepted by another staff actor',async()=>{const {v,q}=await setup(),admin=await login('admin');const r=await send(admin,{type:'order.create',visit_id:v.id,expected_version:1,quote_id:q.quote_id});expect(r.statusCode).toBe(403);expect(r.json().error.code).toBe('FORBIDDEN');expect((await db.pool.query('SELECT consumed_at FROM order_quotes WHERE id=$1',[q.quote_id])).rows[0].consumed_at).toBeNull();});
 it('simultaneous acceptance of one quote has a single effect',async()=>{const {w,v,q}=await setup(),body={type:'order.create',visit_id:v.id,expected_version:1,quote_id:q.quote_id};const responses=await Promise.all([send(w,body),send(w,body)]);expect(responses.map(r=>r.statusCode).sort()).toEqual([200,409]);expect(Number((await db.pool.query("SELECT count(*) FROM command_operations WHERE command_type='order.create'")).rows[0].count)).toBe(1);});
 it('expired quote is rejected without effect',async()=>{const {w,v,q}=await setup();await db.pool.query("UPDATE order_quotes SET expires_at=now()-interval '1 second' WHERE id=$1",[q.quote_id]);const r=await send(w,{type:'order.create',visit_id:v.id,expected_version:1,quote_id:q.quote_id});expect(r.statusCode).toBe(409);expect(r.json().error.code).toBe('QUOTE_EXPIRED');expect(Number((await db.pool.query("SELECT count(*) FROM outbox WHERE type='order.create'")).rows[0].count)).toBe(0);});
 it('kitchen cannot quote an unassigned commercial visit',async()=>{const {v}=await setup(),k=await login('cocina');const r=await app.inject({method:'POST',url:'/v1/pos/quotes',headers:{cookie:k.cookie},payload:{visit_id:v.id,lines:[{product_id:'20000000-0000-4000-8000-000000000001',quantity:1}]}});expect(r.statusCode).toBe(403);});
 it('normalization migration preserves money and history and is repeatable',async()=>{const {w,v,q}=await setup();await send(w,{type:'order.create',visit_id:v.id,expected_version:1,quote_id:q.quote_id});const row=(await db.pool.query('SELECT tenant_id,branch_id,state FROM branch_state WHERE state->>\'tenant_id\'=$1',['90000000-0000-4000-8000-000000000001'])).rows[0];const state=row.state;state.checks[0].fiscal_status='issued';state.fiscal_documents=[{id:randomUUID(),check_id:state.checks[0].id,status:'accepted_simulated'}];await db.pool.query('UPDATE branch_state SET state=$1 WHERE tenant_id=$2 AND branch_id=$3',[JSON.stringify(state),row.tenant_id,row.branch_id]);const sql=await readFile(new URL('../../database/migrations/011_lab_fiscal_pending.sql',import.meta.url),'utf8');await db.pool.query(sql);const after=(await db.pool.query('SELECT state FROM branch_state WHERE tenant_id=$1 AND branch_id=$2',[row.tenant_id,row.branch_id])).rows[0].state;expect(after.checks[0].fiscal_status).toBe('pending');expect(after.checks[0].total_minor).toBe(3500);expect(after.orders).toEqual(state.orders);expect(after.fiscal_documents).toEqual(state.fiscal_documents);await db.pool.query(sql);const twice=(await db.pool.query('SELECT state FROM branch_state WHERE tenant_id=$1 AND branch_id=$2',[row.tenant_id,row.branch_id])).rows[0].state;expect(twice).toEqual(after);});
});
