import { beforeAll, beforeEach, afterAll, it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createApp } from '../../services/commerce/src/app.js';
import { testDatabase, tenant, branch } from '../support/database.js';
let db: Awaited<ReturnType<typeof testDatabase>>, app: Awaited<ReturnType<typeof createApp>>;
beforeAll(async () => { db = await testDatabase(); app = await createApp(db.pool, false); }, 30000);
beforeEach(async () => { await db.reset(); }); afterAll(async () => { await app?.close(); await db?.close(); }, 30000);
async function login(name: string) { const r = await app.inject({ method: 'POST', url: '/v1/pos/session', payload: { username: name, password: 'QatuDemo2026!' } }); expect(r.statusCode).toBe(200); return { cookie: r.cookies[0]!.name + '=' + r.cookies[0]!.value, csrf: r.json().csrf_token }; }
async function raw() { return (await db.pool.query('SELECT state FROM branch_state WHERE tenant_id=$1 AND branch_id=$2', [tenant, branch])).rows[0].state; }
async function send(a: Awaited<ReturnType<typeof login>>, body: any) { return app.inject({ method: 'POST', url: '/v1/pos/commands', headers: { cookie: a.cookie, 'x-csrf-token': a.csrf }, payload: { operation_id: randomUUID(), ...body } }); }
async function large(amount = 5000000000) { const a = await login('admin'); let s = await raw(); s.products[0].price_minor = amount; await db.pool.query('UPDATE branch_state SET state=$3 WHERE tenant_id=$1 AND branch_id=$2', [tenant, branch, JSON.stringify(s)]); expect((await send(a, { type: 'table.open', table_id: s.tables[0].id, expected_version: 1 })).statusCode).toBe(200); s = await raw(); const q = await app.inject({ method: 'POST', url: '/v1/pos/quotes', headers: { cookie: a.cookie }, payload: { visit_id: s.visits[0].id, lines: [{ product_id: s.products[0].id, quantity: 1 }] } }); expect(q.statusCode).toBe(200); const op = { type: 'order.create', visit_id: s.visits[0].id, expected_version: s.visits[0].version, quote_id: q.json().quote_id }; expect((await send(a, op)).statusCode).toBe(200); return a; }
it('persists and reads quotes above int32 without truncation', async () => { await large(); const q = await db.pool.query('SELECT total_minor FROM order_quotes'); expect(String(q.rows[0].total_minor)).toBe('5000000000'); expect((await raw()).checks[0].total_minor).toBe(5000000000); });
it('persists high-value void audit transactionally', async () => { const a = await large(), s = await raw(); expect((await send(a, { type: 'order.line.void', line_id: s.orders[0].lines[0].id, expected_version: s.visits[0].version, quantity: 1, reason: 'Corrección de unidad no entregada', restore_stock: false })).statusCode).toBe(200); expect(String((await db.pool.query('SELECT amount_minor FROM order_void_audit')).rows[0].amount_minor)).toBe('5000000000'); expect((await raw()).checks[0].total_minor).toBe(0); });
it('persists high-value discount without int32 overflow', async () => { const a = await large(), s = await raw(); expect((await send(a, { type: 'check.discount.apply', check_id: s.checks[0].id, expected_version: s.checks[0].version, kind: 'fixed', amount_minor: 3000000000, reason: 'Descuento de prueba de límite' })).statusCode).toBe(200); expect(String((await db.pool.query('SELECT discount_minor FROM check_discount_audit')).rows[0].discount_minor)).toBe('3000000000'); });
it('stores exact safeinteger maximum and rejects SQL beyond that domain', async () => { await large(Number.MAX_SAFE_INTEGER); const row = (await db.pool.query('SELECT id,total_minor FROM order_quotes')).rows[0]; expect(String(row.total_minor)).toBe('9007199254740991'); await expect(db.pool.query('UPDATE order_quotes SET total_minor=$1 WHERE id=$2', ['9007199254740992', row.id])).rejects.toMatchObject({ code: '23514' }); });
it('all six monetary SQL columns are bigint and fiscal totals stay exact above int32',async()=>{
  const a=await large();let s=await raw();expect((await send(a,{type:'cash.open',shift_label:'diurno',opening_minor:0,expected_day_version:s.business_day.version})).statusCode).toBe(200);s=await raw();const auth=await send(a,{type:'collection.authorize',check_id:s.checks[0].id,expected_version:s.checks[0].version,cash_session_id:s.cash_sessions[0].id,method:'cash',amount_minor:5000000000});expect(auth.statusCode).toBe(200);expect((await send(a,{type:'payment.confirm',authorization_id:auth.json().entity_id,received_minor:5000000000})).statusCode).toBe(200);s=await raw();expect((await send(a,{type:'fiscal.document.issue',check_id:s.checks[0].id,expected_check_version:s.checks[0].version,doc_type:'boleta',customer_doc_type:'dni',customer_doc_number:'00000000',customer_name:'PRUEBA SINTÉTICA'})).statusCode).toBe(200);
  const fiscal=(await db.pool.query('SELECT op_gravada_minor,igv_minor,total_minor FROM fiscal_documents')).rows[0];expect(fiscal.total_minor).toBe('5000000000');expect(BigInt(fiscal.op_gravada_minor)+BigInt(fiscal.igv_minor)).toBe(5000000000n);
  const columns=[['order_quotes','total_minor'],['order_void_audit','amount_minor'],['fiscal_documents','op_gravada_minor'],['fiscal_documents','igv_minor'],['fiscal_documents','total_minor'],['check_discount_audit','discount_minor']];for(const [table,column] of columns){const row=await db.pool.query('SELECT data_type FROM information_schema.columns WHERE table_name=$1 AND column_name=$2',[table,column]);expect(row.rows[0].data_type).toBe('bigint');}
});
