import { beforeAll, beforeEach, afterAll, it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createApp } from '../../services/commerce/src/app.js';
import { testDatabase, tenant, branch } from '../support/database.js';
const password = 'IndividualPrueba2026!';
let db: Awaited<ReturnType<typeof testDatabase>>, app: Awaited<ReturnType<typeof createApp>>;
beforeAll(async () => { db = await testDatabase(); app = await createApp(db.pool, false); }, 30000);
beforeEach(async () => { await db.reset(); }); afterAll(async () => { await app?.close(); await db?.close(); }, 30000);
async function login(username = 'admin', pwd = 'QatuDemo2026!', server = app, origin?: string) { const r = await server.inject({ method:'POST', url:'/v1/pos/session', headers: origin ? {origin} : {}, payload:{username,password:pwd} }); expect(r.statusCode).toBe(200); return {cookie:r.cookies[0]!.name+'='+r.cookies[0]!.value, csrf:r.json().csrf_token}; }
async function raw() { return (await db.pool.query('SELECT state FROM branch_state WHERE tenant_id=$1 AND branch_id=$2',[tenant,branch])).rows[0].state; }
async function send(a: Awaited<ReturnType<typeof login>>, body:any, server=app, origin?:string) { return server.inject({method:'POST',url:'/v1/pos/commands',headers:{cookie:a.cookie,'x-csrf-token':a.csrf,...(origin ? {origin} : {})},payload:{operation_id:randomUUID(),...body}}); }
async function create(a:Awaited<ReturnType<typeof login>>, username='apoyo') { const r=await send(a,{type:'staff.create',username,name:'Apoyo salón',role:'waiter',station:null,reason:'Alta individual de prueba'}); expect(r.statusCode).toBe(200); return r.json().snapshot.staff.find((s:any)=>s.username===username); }
async function credential(a:Awaited<ReturnType<typeof login>>, s:any, extra:any={}) { return app.inject({method:'POST',url:`/v1/pos/staff/${s.id}/password`,headers:{cookie:a.cookie,'x-csrf-token':a.csrf},payload:{expected_version:s.version,current_password:'QatuDemo2026!',new_password:password,reason:'Contraseña de prueba individual',...extra}}); }
const update=(s:any,extra:any={})=>({type:'staff.update',staff_id:s.id,expected_version:s.version,name:s.name,role:s.role,station:s.station,active:true,reason:'Revisión de acceso individual',...extra});
it.each(['password','profile'])('rolls back %s when the target SQL membership is missing',async(kind)=>{
  const a=await login(),s=await create(a);await db.pool.query('DELETE FROM staff_memberships WHERE id=$1',[s.id]);
  const before=await raw(),operations=(await db.pool.query('SELECT * FROM command_operations ORDER BY operation_id')).rows,outbox=(await db.pool.query('SELECT * FROM outbox ORDER BY operation_id')).rows;
  const r=kind==='password'?await credential(a,s):await send(a,update(s,{active:false,name:'Nombre revisado'}));
  expect(r.statusCode).toBe(409);expect(r.json().error.code).toBe('IDENTITY_PROJECTION_MISMATCH');expect(await raw()).toEqual(before);
  expect((await db.pool.query('SELECT * FROM command_operations ORDER BY operation_id')).rows).toEqual(operations);expect((await db.pool.query('SELECT * FROM outbox ORDER BY operation_id')).rows).toEqual(outbox);
});
it('new membership is inactive, has no usable demo password, and cannot activate until credential exists',async()=>{const a=await login(),s=await create(a); expect(s).toMatchObject({active:false,credential_ready:false,version:1});expect((await send(a,update(s))).statusCode).toBe(409);expect((await app.inject({method:'POST',url:'/v1/pos/session',payload:{username:s.username,password:'QatuDemo2026!'}})).statusCode).toBe(401);expect((await db.pool.query('SELECT active FROM staff_memberships WHERE id=$1',[s.id])).rows[0].active).toBe(false);});
it('sets hash privately, activates account, and enforces waiter authority',async()=>{const a=await login(),s=await create(a);expect((await credential(a,s)).statusCode).toBe(200);let state=await raw(),target=state.staff.find((u:any)=>u.id===s.id);expect(target.version).toBe(2);expect(target.active).toBe(false);const row=(await db.pool.query('SELECT password_hash,password_salt FROM staff_memberships WHERE id=$1',[s.id])).rows[0];expect(row.password_hash).not.toBe(password);expect((await send(a,update(target))).statusCode).toBe(200);const w=await login(s.username,password);expect((await send(w,{type:'staff.create',username:'intruso',name:'Intruso',role:'admin',station:null,reason:'No permitido'})).statusCode).toBe(403);const safe=JSON.stringify({state:await raw(),operations:(await db.pool.query('SELECT * FROM command_operations')).rows,outbox:(await db.pool.query('SELECT * FROM outbox')).rows});for(const secret of [password,'QatuDemo2026!',row.password_hash,row.password_salt])expect(safe).not.toContain(secret);});
it('wrong administrative password leaves state, hash, sessions, and outbox unchanged',async()=>{const a=await login(),s=await create(a),before=await raw(),rows=(await db.pool.query('SELECT * FROM staff_memberships ORDER BY id')).rows,n=Number((await db.pool.query('SELECT count(*) FROM outbox')).rows[0].count);expect((await credential(a,s,{current_password:'incorrecta'})).statusCode).toBe(403);expect(await raw()).toEqual(before);expect((await db.pool.query('SELECT * FROM staff_memberships ORDER BY id')).rows).toEqual(rows);expect(Number((await db.pool.query('SELECT count(*) FROM outbox')).rows[0].count)).toBe(n);expect((await app.inject({url:'/v1/pos/session',headers:{cookie:a.cookie}})).statusCode).toBe(200);});
it('rejects credential write without CSRF and outside current tenant',async()=>{const a=await login(),s=await create(a);expect((await app.inject({method:'POST',url:`/v1/pos/staff/${s.id}/password`,headers:{cookie:a.cookie},payload:{expected_version:1,current_password:'QatuDemo2026!',new_password:password,reason:'Prueba CSRF'}})).statusCode).toBe(403);const other=await login('otro_admin');expect((await credential(other,s)).statusCode).toBe(404);expect((await raw()).staff.find((u:any)=>u.id===s.id).version).toBe(1);});
it('concurrent credential writes serialize and invalidate the old session',async()=>{const a=await login(),s=(await raw()).staff.find((u:any)=>u.username==='mozo'),w=await login('mozo');s.version=1;const results=await Promise.all([credential(a,s),credential(a,s)]);expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);expect((await app.inject({url:'/v1/pos/session',headers:{cookie:w.cookie}})).statusCode).toBe(401);expect(Number((await db.pool.query("SELECT count(*) FROM outbox WHERE type='staff.password'")).rows[0].count)).toBe(1);expect((await login('mozo',password)).cookie).toBeTruthy();});
it('profile edit revokes old session and blocks deactivation of responsible waiter',async()=>{const a=await login(),w=await login('mozo');let state=await raw(),s=state.staff.find((u:any)=>u.username==='mozo');expect((await send(a,update({...s,version:1},{name:'Mozo revisado'}))).statusCode).toBe(200);expect((await app.inject({url:'/v1/pos/session',headers:{cookie:w.cookie}})).statusCode).toBe(401);const next=await login('mozo');state=await raw();expect((await send(next,{type:'table.open',table_id:state.tables[0].id,expected_version:1})).statusCode).toBe(200);state=await raw();s=state.staff.find((u:any)=>u.username==='mozo');const before=structuredClone(state);expect((await send(a,update(s,{active:false}))).statusCode).toBe(409);expect(await raw()).toEqual(before);});
it('competing profile updates have one durable winner; duplicate username never corrupts membership',async()=>{const a=await login(),s=await create(a);const results=await Promise.all([send(a,update(s,{active:false,name:'Apoyo uno'})),send(a,update(s,{active:false,name:'Apoyo dos'}))]);expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);const before=await raw();expect((await send(a,{type:'staff.create',username:s.username,name:'Duplicado',role:'waiter',station:null,reason:'Prueba duplicado'})).statusCode).toBe(400);expect(await raw()).toEqual(before);expect(Number((await db.pool.query('SELECT count(*) FROM staff_memberships WHERE username=$1',[s.username])).rows[0].count)).toBe(1);});
it('stock reception persists once, retains finance and rejects a reused document with a new operation',async()=>{const a=await login(),before=await raw(),s=before.stock[0],op=randomUUID(),body={type:'stock.receive',operation_id:op,stock_item_id:s.id,expected_version:s.version,quantity:12,receipt_reference:' guIa-001 ',reason:'Entrega física revisada'};const r=await send(a,body);expect(r.statusCode).toBe(200);expect((await send(a,body)).json().replayed).toBe(true);const next=await raw();expect(next.stock[0].on_hand).toBe(s.on_hand+12);expect(next.stock_movements.filter((m:any)=>m.kind==='receipt')).toHaveLength(1);expect(next.stock_movements.at(-1).receipt_reference).toBe('GUIA-001');for(const key of ['cash_sessions','payments','cash_movements','checks'])expect(next[key]).toEqual(before[key]);const rejected=await send(a,{...body,operation_id:randomUUID(),expected_version:next.stock[0].version});expect(rejected.statusCode).toBe(409);expect(await raw()).toEqual(next);});
it('cashier needs own open session for a reception and cannot receive Heladería',async()=>{const c=await login('caja'),before=await raw(),s=before.stock[0],body={type:'stock.receive',stock_item_id:s.id,expected_version:s.version,quantity:1,receipt_reference:'GUIA-TEST',reason:'Entrega física revisada'};expect((await send(c,body)).statusCode).toBe(409);expect(await raw()).toEqual(before);expect((await send(c,{type:'cash.open',shift_label:'diurno',opening_minor:0,expected_day_version:before.business_day.version})).statusCode).toBe(200);expect((await send(c,{...body,stock_item_id:before.stock[3].id})).statusCode).toBe(403);expect((await send(c,body)).statusCode).toBe(200);});
it('new SKU is empty, tenant protected and unit tracked after reception',async()=>{const a=await login();const r=await send(a,{type:'stock.create',sku:'CERVEZA-NEW',name:'Cerveza nueva',station:'caja',beverage_kind:'beer',reason:'Alta física de SKU'});expect(r.statusCode).toBe(200);const s=r.json().snapshot.stock.find((s:any)=>s.sku==='CERVEZA-NEW');expect(s).toMatchObject({on_hand:0,reserved:0,available:0,version:1});const other=await login('otro_admin');expect((await send(other,{type:'stock.receive',stock_item_id:s.id,expected_version:1,quantity:4,receipt_reference:'GUIA-NEW',reason:'Entrega física revisada'})).statusCode).toBe(404);expect((await raw()).stock.find((x:any)=>x.id===s.id).on_hand).toBe(0);});
it('operational mode requires exact origin, secure cookie and matching persisted environment',async()=>{const origin='https://pos.example.test',op=await createApp(db.pool,false,{environment:'operational',public_origin:origin,secure_cookies:true});try{const payload={username:'admin',password:'QatuDemo2026!'};expect((await op.inject({method:'POST',url:'/v1/pos/session',payload})).statusCode).toBe(403);expect((await op.inject({method:'POST',url:'/v1/pos/session',headers:{origin},payload})).statusCode).toBe(403);const s=await raw();s.environment='operational';await db.pool.query('UPDATE branch_state SET state=$3 WHERE tenant_id=$1 AND branch_id=$2',[tenant,branch,JSON.stringify(s)]);expect((await app.inject({method:'POST',url:'/v1/pos/session',payload})).statusCode).toBe(403);const r=await op.inject({method:'POST',url:'/v1/pos/session',headers:{origin},payload});expect(r.statusCode).toBe(200);expect(r.headers['set-cookie']).toContain('Secure');const a=await login('admin','QatuDemo2026!',op,origin);expect((await send(a,{type:'cash.open',shift_label:'diurno',opening_minor:0,expected_day_version:s.business_day.version},op,'https://evil.example')).statusCode).toBe(403);expect((await send(a,{type:'cash.open',shift_label:'diurno',opening_minor:0,expected_day_version:s.business_day.version},op,origin)).statusCode).toBe(200);expect((await send(a,{type:'print.ack',print_job_id:randomUUID(),expected_version:1,state:'confirmed',evidence:'No habilitar acuse ficticio'},op,origin)).statusCode).toBe(409);}finally{await op.close();}});
it('a revoked session cannot complete a command already waiting on the branch lock',async()=>{
  const a=await login(),w=await login('mozo'),s=await raw(),client=await db.pool.connect();let pending:Promise<any>|undefined;
  try { await client.query('BEGIN');await client.query('SELECT version FROM branch_state WHERE tenant_id=$1 AND branch_id=$2 FOR UPDATE',[tenant,branch]);
    pending=send(w,{type:'table.open',table_id:s.tables[0].id,expected_version:1});
    let waiting=false;for(let n=0;n<100;n++){const q=await db.pool.query("SELECT count(*) FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND query LIKE '%branch_state%FOR UPDATE%'");if(Number(q.rows[0].count)>0){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}expect(waiting).toBe(true);
    const id=s.staff.find((u:any)=>u.username==='mozo').id;await client.query('DELETE FROM staff_sessions WHERE tenant_id=$1 AND branch_id=$2 AND staff_id=$3',[tenant,branch,id]);await client.query('COMMIT');const r=await pending;expect(r.statusCode).toBe(401);expect(await raw()).toEqual(s);expect(Number((await db.pool.query('SELECT count(*) FROM outbox')).rows[0].count)).toBe(0);
  } finally {await client.query('ROLLBACK');client.release();if(pending)await pending;}
});
it('operational cash is durable local collection and digital authorization is rejected without effects',async()=>{
  const origin='https://pos.example.test',op=await createApp(db.pool,false,{environment:'operational',public_origin:origin,secure_cookies:true});try{
    let s=await raw();s.environment='operational';await db.pool.query('UPDATE branch_state SET state=$3 WHERE tenant_id=$1 AND branch_id=$2',[tenant,branch,JSON.stringify(s)]);const a=await login('admin','QatuDemo2026!',op,origin);
    expect((await send(a,{type:'cash.open',shift_label:'diurno',opening_minor:0,expected_day_version:s.business_day.version},op,origin)).statusCode).toBe(200);expect((await send(a,{type:'table.open',table_id:s.tables[0].id,expected_version:1},op,origin)).statusCode).toBe(200);s=await raw();const v=s.visits[0];const q=await op.inject({method:'POST',url:'/v1/pos/quotes',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload:{visit_id:v.id,lines:[{product_id:s.products[0].id,quantity:1}]}});expect(q.statusCode).toBe(200);const badQuote=await op.inject({method:'POST',url:'/v1/pos/quotes',headers:{cookie:a.cookie},payload:{visit_id:v.id,lines:[{product_id:s.products[0].id,quantity:1}]}});expect(badQuote.statusCode).toBe(403);expect(Number((await db.pool.query('SELECT count(*) FROM order_quotes')).rows[0].count)).toBe(1);expect((await send(a,{type:'order.create',visit_id:v.id,expected_version:v.version,quote_id:q.json().quote_id},op,origin)).statusCode).toBe(200);s=await raw();const check=s.checks[0],cash=s.cash_sessions[0],before=structuredClone(s),auth={type:'collection.authorize',check_id:check.id,expected_version:check.version,cash_session_id:cash.id,method:'yape',amount_minor:check.total_minor};expect((await send(a,auth,op,origin)).statusCode).toBe(409);expect(await raw()).toEqual(before);
    const result=await send(a,{...auth,method:'cash'},op,origin);expect(result.statusCode).toBe(200);expect((await raw()).authorizations[0].registry_ack).toBe('local_authority');expect((await send(a,{type:'payment.confirm',authorization_id:result.json().entity_id,received_minor:check.total_minor},op,origin)).statusCode).toBe(200);s=await raw();expect(s.checks[0].paid_minor).toBe(check.total_minor);expect(s.cash_sessions[0].expected_minor).toBe(check.total_minor);expect(s.payments[0].status).toBe('succeeded');expect(s.checks[0].fiscal_status).toBe('pending');
  }finally{await op.close();}
});
it('operational guest quotes require origin and CSRF, and guest reads cannot cross installation modes',async()=>{
  const origin='https://pos.example.test',op=await createApp(db.pool,false,{environment:'operational',public_origin:origin,secure_cookies:true});try{
    let s=await raw();s.environment='operational';await db.pool.query('UPDATE branch_state SET state=$3 WHERE tenant_id=$1 AND branch_id=$2',[tenant,branch,JSON.stringify(s)]);const a=await login('mozo','QatuDemo2026!',op,origin);expect((await send(a,{type:'table.open',table_id:s.tables[0].id,expected_version:1},op,origin)).statusCode).toBe(200);s=await raw();const v=s.visits[0];expect((await send(a,{type:'guest.access',visit_id:v.id,expected_version:v.version,action:'activate',reason:'Acceso sintético cliente autorizado'},op,origin)).statusCode).toBe(200);
    const access=await op.inject({url:'/v1/pos/guest-access/'+v.id,headers:{cookie:a.cookie}});expect(access.statusCode).toBe(200);const joined=await op.inject({method:'POST',url:'/v1/guest/session',headers:{origin},payload:{code:access.json().code}});expect(joined.statusCode).toBe(200);const cookie=joined.cookies[0]!.name+'='+joined.cookies[0]!.value,csrf=joined.json().csrf_token,payload={lines:[{product_id:s.products[0].id,quantity:1}]};
    for(const headers of [{cookie},{cookie,origin}])expect((await op.inject({method:'POST',url:'/v1/guest/quotes',headers,payload})).statusCode).toBe(403);expect(Number((await db.pool.query('SELECT count(*) FROM order_quotes')).rows[0].count)).toBe(0);const result=await op.inject({method:'POST',url:'/v1/guest/quotes',headers:{cookie,origin,'x-csrf-token':csrf},payload});expect(result.statusCode).toBe(200);expect(Number((await db.pool.query('SELECT count(*) FROM order_quotes')).rows[0].count)).toBe(1);for(const url of ['/v1/guest/session','/v1/guest/snapshot']){expect((await op.inject({url,headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({url,headers:{cookie}})).statusCode).toBe(403);}
  }finally{await op.close();}
});
