import { describe,it,expect } from 'vitest';
import { mkdtemp,writeFile,symlink,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { loadProtectedConfig,validateProtectedConfig,protectedEnvironment } from '../../scripts/cloud/protected.js';
const ref='abcdefghijklmnopqrst';
const valid={QATU_DEPLOYMENT:'vercel',QATU_ENV:'production',QATU_DEPLOYMENT_STAGE:'production',QATU_SUPABASE_PROJECT_REF:ref,QATU_PUBLIC_ORIGIN:'https://pos.example.test',QATU_GUEST_CODE_KEY_BASE64:Buffer.alloc(32,71).toString('base64'),DATABASE_URL:`postgresql://qatu_pos_runtime.${ref}:SyntheticRuntimeOnly2026@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=verify-full`,QATU_MAINTENANCE_DATABASE_URL:`postgresql://postgres.${ref}:SyntheticAdminOnly2026@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=verify-full`,QATU_RUNTIME_DATABASE_PASSWORD:'SyntheticRuntimeOnly2026',QATU_ADMIN_USERNAME:'admin_individual',QATU_ADMIN_NAME:'Administrador sintético',QATU_ADMIN_PASSWORD:'SyntheticAdminOnly2026',QATU_RESTAURANT_NAME:'Local sintético',QATU_TABLE_COUNT:'10'};
describe('configuration for a specified cloud project',()=>{
 it('validates without connecting and keeps staging explicit',()=>{expect(()=>validateProtectedConfig(valid,'check')).not.toThrow();expect(()=>validateProtectedConfig({...valid,QATU_DEPLOYMENT_STAGE:'staging'},'check')).not.toThrow();});
 it.each([
  {NEXT_PUBLIC_DATABASE_URL:'secret'}, {QATU_DEPLOYMENT_STAGE:'preview'}, {QATU_PUBLIC_ORIGIN:'https://pos.example.test/'},
  {QATU_SUPABASE_PROJECT_REF:'anotherproject'}, {QATU_GUEST_CODE_KEY_BASE64:'invalid'}, {QATU_TABLE_COUNT:'0'},
  {DATABASE_URL:valid.DATABASE_URL.replace(':5432/',':6543/')}, {DATABASE_URL:valid.DATABASE_URL.replace('verify-full','require')},
  {DATABASE_URL:valid.QATU_MAINTENANCE_DATABASE_URL}, {QATU_RUNTIME_DATABASE_PASSWORD:'short'},
 ])('rejects incomplete or unsafe settings without disclosing values',patch=>{expect(()=>validateProtectedConfig({...valid,...patch},'check')).toThrow('Protected cloud configuration is invalid.');});
 it('checks runtime credential corresponds to installed role',()=>{expect(()=>validateProtectedConfig({...valid,DATABASE_URL:valid.DATABASE_URL.replace('SyntheticRuntimeOnly2026','DifferentPassword2026')},'check')).toThrow();});
 it('doctor uses runtime only; migrate uses maintenance only',()=>{const runtime={...valid};delete (runtime as Partial<typeof valid>).QATU_MAINTENANCE_DATABASE_URL;expect(()=>validateProtectedConfig(runtime,'doctor')).not.toThrow();expect(()=>validateProtectedConfig(runtime,'migrate')).toThrow();});
 it('clears inherited lab, preview and browser credentials',()=>{const env=protectedEnvironment(valid,{PATH:'test-path',QATU_ENV:'test',QATU_WEB_PORT:'3100',VERCEL_ENV:'preview',NEXT_PUBLIC_SECRET:'x',DATABASE_URL:'lab',PGPASSWORD:'x',PGOPTIONS:'x'});expect(env.PATH).toBe('test-path');expect(env.DATABASE_URL).toBe(valid.DATABASE_URL);for(const key of ['QATU_WEB_PORT','VERCEL_ENV','NEXT_PUBLIC_SECRET','PGPASSWORD','PGOPTIONS'])expect(env[key]).toBeUndefined();});
 it('does not pass maintenance or initial admin credentials to doctor',()=>{const env=protectedEnvironment(valid,{},'doctor');expect(env.DATABASE_URL).toBe(valid.DATABASE_URL);for(const key of ['QATU_MAINTENANCE_DATABASE_URL','QATU_RUNTIME_DATABASE_PASSWORD','QATU_ADMIN_PASSWORD','QATU_ADMIN_USERNAME'])expect(env[key]).toBeUndefined();});
 it('does not pass runtime or initial admin credentials to migrate',()=>{const env=protectedEnvironment(valid,{},'migrate');expect(env.QATU_MAINTENANCE_DATABASE_URL).toBe(valid.QATU_MAINTENANCE_DATABASE_URL);for(const key of ['DATABASE_URL','QATU_RUNTIME_DATABASE_PASSWORD','QATU_ADMIN_PASSWORD','QATU_ADMIN_USERNAME'])expect(env[key]).toBeUndefined();});
 it('rejects non-string keys, arrays and unknown command',()=>{for(const value of [[],{...valid,QATU_TABLE_COUNT:10},{...valid,EXTRA:'x'}])expect(()=>validateProtectedConfig(value,'check')).toThrow();expect(()=>validateProtectedConfig(valid,'seed')).toThrow();});
 it('loads only external files, rejecting lexical and resolved internal paths',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'qatu-protected-'));try{const checkout=path.join(dir,'checkout'),external=path.join(dir,'config.json');await writeFile(external,JSON.stringify(valid));await import('node:fs/promises').then(fs=>fs.mkdir(checkout));const internal=path.join(checkout,'config.json');await writeFile(internal,JSON.stringify(valid));expect(await loadProtectedConfig(external,checkout,'check')).toEqual(valid);await expect(loadProtectedConfig(internal,checkout,'check')).rejects.toThrow();const linked=path.join(dir,'linked-checkout');await symlink(checkout,linked,'junction');await expect(loadProtectedConfig(path.join(linked,'config.json'),checkout,'check')).rejects.toThrow();}finally{await rm(dir,{recursive:true,force:true});}});
 it('rejects oversized and malformed protected files with a safe error',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'qatu-protected-'));try{const f=path.join(dir,'bad.json');await writeFile(f,'x'.repeat(32769));await expect(loadProtectedConfig(f,process.cwd(),'check')).rejects.toThrow('Protected cloud configuration is invalid.');await writeFile(f,'{"QATU_ADMIN_PASSWORD":');await expect(loadProtectedConfig(f,process.cwd(),'check')).rejects.toThrow('Protected cloud configuration is invalid.');}finally{await rm(dir,{recursive:true,force:true});}});
});
