import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createInitialState,executeCommand,createDomainQuote,projectSnapshot,type Actor} from '../../packages/domain/src/index.js';
import {roundRatio} from '../../packages/domain/src/exact.js';
import type {PosCommand} from '@qatu/contracts';
function h() {
 let state=createInitialState({tenant_id:'unit-tenant',branch_id:'unit-branch'});
 const now='2026-10-03T15:00:00.000Z';
 const actor=(name='mozo'):Actor=>({tenant_id:state.tenant_id,branch_id:state.branch.id,user:state.staff.find(u=>u.username===name)!});
 const run=(input:any,name='mozo',quote?:any,time=now)=>{const r=executeCommand(state,actor(name),{...input,operation_id:randomUUID()} as PosCommand,{now:time,id:randomUUID,...(quote?{quote}:{})});state=r.state;return r;};
 run({type:'table.open',table_id:state.tables[0]!.id,expected_version:1});
 const quote=(qty=2)=>createDomainQuote(state,state.visits[0]!.id,[{product_id:state.products[0]!.id,quantity:qty}],now,randomUUID(),actor());
 const order=(q=quote(),name='mozo')=>run({type:'order.create',visit_id:state.visits[0]!.id,expected_version:state.visits[0]!.version,quote_id:q.id},name,q);
 const discount=(kind='percentage',value=10)=>run({type:'check.discount.apply',check_id:state.checks[0]!.id,expected_version:state.checks[0]!.version,kind,...(kind==='percentage'?{percent:value}:{amount_minor:value}),reason:'Descuento de prueba'},'caja');
 const cash=()=>run({type:'cash.open',opening_minor:0,shift_label:'diurno',expected_day_version:state.business_day.version},'caja');
 const pay=()=>{const a=run({type:'collection.authorize',check_id:state.checks[0]!.id,expected_version:state.checks[0]!.version,cash_session_id:state.cash_sessions[0]!.id,method:'cash',amount_minor:state.checks[0]!.remaining_collectible_minor},'caja');run({type:'payment.confirm',authorization_id:a.entity_id,received_minor:state.checks[0]!.total_minor},'caja');};
 const issue=(doc_type='boleta')=>run({type:'fiscal.document.issue',check_id:state.checks[0]!.id,expected_check_version:state.checks[0]!.version,doc_type,customer_doc_type:doc_type==='factura'?'ruc':'sin_documento',customer_doc_number:doc_type==='factura'?'20601234567':undefined,customer_name:'CLIENTE SINTETICO'},'caja');
 return {actor,run,quote,order,discount,cash,pay,issue,now,get state(){return state;}};
}
describe('commercial corrective011',()=>{
 it('rejects a consumed quote without repeating the order',()=>{const t=h(),q=t.quote();t.order(q);const before=structuredClone(t.state);q.consumed_at=t.now;expect(()=>t.order(q)).toThrow('ya se utilizó');expect(t.state).toEqual(before);});
 it('rejects another staff actor quote',()=>{const t=h();expect(()=>t.order(t.quote(),'admin')).toThrow('otro participante');expect(t.state.orders).toHaveLength(0);});
 it('rejects quotes from another branch',()=>{const t=h(),q=t.quote();q.branch_id='other';expect(()=>t.order(q)).toThrow('otro local');});
 it('rejects a guest quote on staff endpoint',()=>{const t=h(),q=t.quote();q.principal_kind='guest';q.guest_session_id=randomUUID();expect(()=>t.order(q)).toThrow('otro participante');});
 it('expires at the exact limit',()=>{const t=h(),q=t.quote();expect(()=>t.run({type:'order.create',visit_id:q.visit_id,expected_version:1,quote_id:q.id},'mozo',q,q.expires_at)).toThrow('expirado');});
 it('denies kitchen quotes',()=>{const t=h();expect(()=>createDomainQuote(t.state,t.state.visits[0]!.id,[{product_id:t.state.products[0]!.id,quantity:1}],t.now,randomUUID(),t.actor('cocina'))).toThrow('perfil');});
 it('does not reopen a paid discounted check by removal',()=>{const t=h();t.order();t.discount();t.cash();t.pay();const before=structuredClone(t.state);expect(()=>t.run({type:'check.discount.remove',check_id:t.state.checks[0]!.id,expected_version:t.state.checks[0]!.version,reason:'Retirar ya pagado'},'caja')).toThrow('antes');expect(t.state).toEqual(before);});
 it('does not reopen paid check by replacing discount with smaller one',()=>{const t=h();t.order();t.discount();t.cash();t.pay();expect(()=>t.discount('fixed',100)).toThrow('No se reabre');expect(t.state.checks[0]!.remaining_collectible_minor).toBe(0);});
 it('rounds large percentage money exactly',()=>{expect(roundRatio(Number.MAX_SAFE_INTEGER,28,100)).toBe(2522015791327477);expect(roundRatio(1,50,100)).toBe(1);expect(()=>roundRatio(Number.MAX_SAFE_INTEGER,2,1)).toThrow('límite exacto');});
 it('uses exact large discount in domain',()=>{const t=h();t.state.products[0]!.price_minor=Number.MAX_SAFE_INTEGER;t.order(t.quote(1));t.discount('percentage',28);expect(t.state.checks[0]!.discount_minor).toBe(2522015791327477);});
 it('hides discount audit from waiter and kitchen',()=>{const t=h();t.order();t.discount();expect(projectSnapshot(t.state,t.actor()).discount_audit).toEqual([]);expect(projectSnapshot(t.state,t.actor('cocina')).discount_audit).toEqual([]);expect(projectSnapshot(t.state,t.actor('caja')).discount_audit).toHaveLength(1);});
 it('closes with net sales after discount and void rather than gross original lines',()=>{const t=h();t.order();t.discount();const l=t.state.orders[0]!.lines[0]!;t.run({type:'order.line.void',line_id:l.id,expected_version:t.state.visits[0]!.version,quantity:1,restore_stock:false,reason:'Anulación parcial sintética'},'caja');t.cash();t.run({type:'day.close',cash_session_id:t.state.cash_sessions[0]!.id,expected_version:t.state.cash_sessions[0]!.version,expected_day_version:t.state.business_day.version,counted_cash_minor:0,stock_counts:t.state.stock.filter(s=>s.station==='caja').map(s=>({stock_item_id:s.id,counted_quantity:s.on_hand})),reason:'Cierre de prueba'},'caja');expect(t.state.day_closes[0]!.sales_minor).toBe(2800);expect(t.state.day_closes[0]!.collections_minor).toBe(0);});
 it('simulation does not establish fiscal acceptance or clear obligation',()=>{const t=h();t.order();t.cash();t.pay();t.issue();expect(t.state.checks[0]!.fiscal_status).toBe('pending');expect(t.state.fiscal_documents[0]!.status).toBe('accepted_simulated');expect(projectSnapshot(t.state,t.actor('caja')).capabilities.fiscal_issuance).toBe(false);t.run({type:'day.close',cash_session_id:t.state.cash_sessions[0]!.id,expected_version:t.state.cash_sessions[0]!.version,expected_day_version:t.state.business_day.version,counted_cash_minor:7000,stock_counts:t.state.stock.filter(s=>s.station==='caja').map(s=>({stock_item_id:s.id,counted_quantity:s.on_hand})),reason:'Cierre con obligación pendiente'},'caja');expect(t.state.day_closes[0]!.pending_fiscal_check_ids).toContain(t.state.checks[0]!.id);});
 for(const reason of ['03','07']) it('rejects unsupported adjustment '+reason+' without altering paid/document state',()=>{const t=h();t.order();t.cash();t.pay();t.issue();const before=structuredClone(t.state);expect(()=>t.run({type:'fiscal.credit_note.issue',document_id:t.state.fiscal_documents[0]!.id,reason_code:reason,reason_description:'Ajuste de prueba'},'caja')).toThrow('contrato específico');expect(t.state).toEqual(before);});
 it('rejects reason02 on boleta',()=>{const t=h();t.order();t.cash();t.pay();t.issue();expect(()=>t.run({type:'fiscal.credit_note.issue',document_id:t.state.fiscal_documents[0]!.id,reason_code:'02',reason_description:'Error en documento'},'caja')).toThrow('solo aplica a factura');});
 it('full simulated credit does not change money or stock',()=>{const t=h();t.order();t.cash();t.pay();t.issue();const payments=structuredClone(t.state.payments),stock=structuredClone(t.state.stock),cash=structuredClone(t.state.cash_sessions),paid=t.state.checks[0]!.paid_minor;t.run({type:'fiscal.credit_note.issue',document_id:t.state.fiscal_documents[0]!.id,reason_code:'01',reason_description:'Reversión sintética total'},'caja');expect(t.state.payments).toEqual(payments);expect(t.state.stock).toEqual(stock);expect(t.state.cash_sessions).toEqual(cash);expect(t.state.checks[0]!.paid_minor).toBe(paid);expect(()=>t.discount('fixed',100)).toThrow('documento simulado');});
});
