import { describe, it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createInitialState, executeCommand, type Actor } from '../../packages/domain/src/index.js';
import { createOperationalState } from '../../packages/domain/src/operational.js';
import { runtimeConfig, originAllowed, assertDatabaseUrl } from '../../services/commerce/src/platform/runtime.js';
import { sqlMoney } from '../../services/commerce/src/platform/money.js';
import { parseMoney, money } from '../../apps/pos/src/lib/client.js';
function h() { let state = createInitialState({ tenant_id: randomUUID(), branch_id: randomUUID() }); const run = (body: any, username = 'admin') => { const actor: Actor = { tenant_id: state.tenant_id, branch_id: state.branch.id, user: state.staff.find(s => s.username === username)! }; const r = executeCommand(state, actor, { operation_id: randomUUID(), ...body }, { now: '2026-10-03T12:00:00Z', id: randomUUID }); state = r.state; return r; }; return { run, get state() { return state; }, setMode() { state.environment = 'operational'; } }; }
const production = { QATU_ENV: 'production', QATU_PUBLIC_ORIGIN: 'https://pos.example.test', DATABASE_URL: 'postgresql://operational_user:synthetic_only_password@127.0.0.1/qatupos_prod_test' };
describe('015 exact money', () => {
  it.each(['5000000000','9007199254740991',5000000000,0])('reads exact SQL money %s', input => expect(sqlMoney(input)).toBe(Number(input)));
  it.each(['9007199254740992','-1','1.5','',null,Infinity,1.5,9007199254740992])('rejects unsafe SQL value %s', input => expect(() => sqlMoney(input)).toThrow());
  it('formats and parses safeinteger cents without binary rounding', () => { expect(parseMoney('90071992547409.91')).toBe(Number.MAX_SAFE_INTEGER); expect(money(Number.MAX_SAFE_INTEGER)).toContain('90,071,992,547,409.91'); expect(money(-Number.MAX_SAFE_INTEGER)).toContain('-S/'); expect(() => parseMoney('90071992547409.92')).toThrow(); });
});
describe('015 operational isolation', () => {
  it('requires exact HTTPS public origin and no default mode switch', () => { expect(runtimeConfig({})).toMatchObject({ environment: 'laboratory', secure_cookies: false }); expect(runtimeConfig(production)).toMatchObject({ environment: 'operational', secure_cookies: true }); });
  it.each(['http://pos.example.test','https://pos.example.test/','https://user@pos.example.test','https://pos.example.test/path','https://pos.example.test#fragment','https://pos.example.test?x=1'])('rejects unsafe public origin %s', origin => expect(() => runtimeConfig({ ...production, QATU_PUBLIC_ORIGIN: origin })).toThrow());
  it('requires origin on operational mutations and ignores nearby domains', () => { const config = runtimeConfig(production); expect(originAllowed(config, undefined)).toBe(false); expect(originAllowed(config, 'https://pos.example.test')).toBe(true); expect(originAllowed(config, 'https://pos.example.test.evil.test')).toBe(false); });
  it.each(['postgresql://qatu_lab:qatu_lab_local_only@127.0.0.1/qatupos_lab','postgresql://op:pass@127.0.0.1/qatupos_prod','postgresql://op:pass@db.example.test/qatupos_prod_test','https://op:pass@127.0.0.1/qatupos_prod_test'])('rejects inappropriate operational DB %s', url => expect(() => assertDatabaseUrl(url, { ...production, DATABASE_URL: url })).toThrow());
  it('accepts separate loopback and verified remote production connections', () => { expect(assertDatabaseUrl(production.DATABASE_URL, production).pathname).toBe('/qatupos_prod_test'); const url='postgresql://op:synthetic@db.example.test/qatupos_prod_test?sslmode=verify-full'; expect(assertDatabaseUrl(url, { ...production, DATABASE_URL: url }).hostname).toBe('db.example.test'); });
  it('initializes real profile without synthetic stock/products/sales/fiscal series', () => { const admin = { id: randomUUID(), username: 'op_admin', name: 'Synthetic operational admin', role: 'admin' as const, station: null }; const s = createOperationalState({ tenant_id: randomUUID(), branch_id: randomUUID(), branch_name: 'Operational test branch' }, admin, 20, '2026-10-04T01:00:00Z'); expect(() => createOperationalState({ tenant_id: randomUUID(), branch_id: randomUUID(), branch_name: 'Test' }, { ...admin, name: 'A'.repeat(101) }, 1)).toThrow('Incomplete'); expect(s.environment).toBe('operational'); expect(s.products).toEqual([]); expect(s.stock_movements).toEqual([]); expect(s.stock).toEqual([]); expect(s.fiscal_documents).toEqual([]); expect(s.tables).toHaveLength(20); expect(s.staff).toHaveLength(1); expect(s.business_day.business_date).toBe('2026-10-03'); expect(JSON.stringify(s)).not.toContain('laboratory-postgres'); });
  it.each(['fiscal.document.issue','fiscal.credit_note.issue','print.ack','payment.resolve','payment.unknown'])('blocks simulated operation %s before effects', type => { const t = h(); t.setMode(); const before = structuredClone(t.state); expect(() => t.run({ type })).toThrow('integración'); expect(t.state).toEqual(before); });
});
describe('015 identity guards', () => {
  const create = { type: 'staff.create', username: 'mozo_individual', name: 'Mozo individual sintético', role: 'waiter', station: null, reason: 'Preparar identidad de prueba' };
  it('new identity is inactive until own credential is initialized', () => { const t = h(), r = t.run(create); const s = t.state.staff.find(s => s.id === r.entity_id)!; expect(s).toMatchObject({ active: false, credential_ready: false, version: 1 }); expect(() => t.run({ type: 'staff.update', staff_id: s.id, expected_version: 1, name: s.name, role: s.role, station: null, active: true, reason: 'Activar sin contraseña' })).toThrow('contraseña'); });
  it.each(['mozo','caja','cocina'])('cannot create staff with %s role', who => { const t = h(); expect(() => t.run(create, who)).toThrow('perfil'); });
  it('cannot remove own administrative authority', () => { const t = h(), admin = t.state.staff.find(s => s.username === 'admin')!; expect(() => t.run({ type: 'staff.update', staff_id: admin.id, expected_version: 1, name: admin.name, role: 'waiter', station: null, active: true, reason: 'Quitar permiso propio' })).toThrow('propio'); });
  it('cannot deactivate waiter responsible for open table', () => { const t = h(); t.run({ type: 'table.open', table_id: t.state.tables[0]!.id, expected_version: 1 }, 'mozo'); const s = t.state.staff[0]!; expect(() => t.run({ type: 'staff.update', staff_id: s.id, expected_version: 1, name: s.name, role: s.role, station: s.station, active: false, reason: 'Relevo con mesa pendiente' })).toThrow('Reasigna'); });
  it('profile rejects a cashier attached to kitchen', () => { const t = h(); expect(() => t.run({ ...create, role: 'cashier', station: 'cocina' })).toThrow('compatibles'); });
});
describe('015 physical stock receipts', () => {
  const create = { type: 'stock.create', name: 'Agua prueba', sku: 'AGUA-TEST', station: 'caja', beverage_kind: 'water', reason: 'Alta de SKU de prueba' };
  it('creates zero stock then receives traceable units without changing money', () => { const t = h(), r = t.run(create), before = structuredClone(t.state.cash_sessions); t.run({ type: 'stock.receive', stock_item_id: r.entity_id, expected_version: 1, quantity: 12, receipt_reference: 'Proveedor A/F001-TEST', reason: 'Ingreso físico verificado' }); const s = t.state.stock.find(s => s.id === r.entity_id)!; expect(s).toMatchObject({ on_hand: 12, reserved: 0, available: 12, version: 2, beverage_kind: 'water' }); expect(t.state.stock_movements.at(-1)).toMatchObject({ kind: 'receipt', quantity_delta: 12 }); expect(t.state.cash_sessions).toEqual(before); });
  it('does not receive same document and SKU twice with different operation IDs', () => { const t = h(), s = t.state.stock[0]!; t.run({ type: 'stock.receive', stock_item_id: s.id, expected_version: 1, quantity: 2, receipt_reference: 'TEST-F001', reason: 'Recepción verificada' }); const before = structuredClone(t.state); expect(() => t.run({ type: 'stock.receive', stock_item_id: s.id, expected_version: 2, quantity: 2, receipt_reference: ' test-f001 ', reason: 'Repetición de documento' })).toThrow('registrados'); expect(t.state).toEqual(before); });
  it('does not receive stock retained for count', () => { const t = h(), s = t.state.stock[0]!; t.run({ type: 'inventory.count', reason: 'Conteo declarado', lines: [{ stock_item_id: s.id, expected_version: 1, counted_quantity: s.on_hand }] }); expect(() => t.run({ type: 'stock.receive', stock_item_id: s.id, expected_version: 1, quantity: 2, receipt_reference: 'TEST-NEW', reason: 'Recepción durante conteo' })).toThrow('conteo'); });
  it('ordinary waiter cannot receive physical stock', () => { const t = h(); expect(() => t.run({ type: 'stock.receive', stock_item_id: t.state.stock[0]!.id, expected_version: 1, quantity: 2, receipt_reference: 'TEST-NEW', reason: 'Ingreso no autorizado' }, 'mozo')).toThrow('perfil'); });
});
