import { describe, it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createInitialState, executeCommand, createDomainQuote, projectSnapshot, type Actor } from '../../packages/domain/src/index.js';
import type { PosCommand } from '@qatu/contracts';
function h() {
  let state = createInitialState({ tenant_id: 'synthetic', branch_id: 'local' });
  state.staff.push({ ...state.staff[0]!, id: randomUUID(), username: 'apoyo', name: 'Mozo de apoyo' });
  let now = '2026-10-03T16:00:00Z';
  const actor = (name: string): Actor => ({ tenant_id: state.tenant_id, branch_id: state.branch.id, user: state.staff.find(s => s.username === name)! });
  const run = (input: any, who = 'mozo', quote?: any) => { const r = executeCommand(state, actor(who), { ...input, operation_id: randomUUID() } as PosCommand, { now, id: randomUUID, ...(quote ? { quote } : {}) }); state = r.state; return r; };
  const cash = (shift = 'diurno', who = 'caja', opening = 0) => run({ type: 'cash.open', shift_label: shift, opening_minor: opening, expected_day_version: state.business_day.version }, who);
  const table = () => { if (!state.visits.length) run({ type: 'table.open', table_id: state.tables[0]!.id, expected_version: 1 }); return state.visits[0]!; };
  const quote = (product = 0, who = 'mozo') => { const visit = table(); return createDomainQuote(state, visit.id, [{ product_id: state.products[product]!.id, quantity: 1 }], now, randomUUID(), actor(who)); };
  const accept = (q: any) => run({ type: 'order.create', visit_id: state.visits[0]!.id, expected_version: state.visits[0]!.version, quote_id: q.id }, 'mozo', q);
  const order = (p = 0) => accept(quote(p));
  const prep = () => run({ type: 'line.prepare', line_id: state.orders[0]!.lines[0]!.id, expected_version: state.orders[0]!.lines[0]!.version, quantity: 1 }, 'cocina');
  const claim = (who = 'mozo', action = 'claim') => run({ type: 'line.claim', line_id: state.orders[0]!.lines[0]!.id, expected_version: state.orders[0]!.lines[0]!.version, action, quantity: action === 'claim' ? 1 : undefined, reason: 'Retiro coordinado' }, who);
  const deliver = (who = 'mozo') => run({ type: 'line.fulfill', line_id: state.orders[0]!.lines[0]!.id, expected_version: state.orders[0]!.lines[0]!.version, quantity: 1 }, who);
  const priority = (who = 'mozo', text = 'Cliente espera por incidencia') => run({ type: 'order.priority', order_id: state.orders[0]!.id, expected_version: (state.orders[0] as any).production_version ?? 1, priority: 'urgent', reason: text }, who);
  const counts = () => state.stock.filter(s => s.station === 'caja').map(s => ({ stock_item_id: s.id, counted_quantity: s.on_hand }));
  const closeBody = (counted = state.cash_sessions.at(-1)!.expected_minor) => ({ cash_session_id: state.cash_sessions.at(-1)!.id, expected_version: state.cash_sessions.at(-1)!.version, expected_day_version: state.business_day.version, counted_cash_minor: counted, stock_counts: counts(), reason: 'Cierre nocturno físico' });
  const final = (counted?: number, approval_id?: string) => run({ type: 'day.close', mode: 'operational_final', ...closeBody(counted), ...(approval_id ? { approval_id } : {}) }, state.cash_sessions.at(-1)!.owner_id === actor('noche').user.id ? 'noche' : 'caja');
  const approve = (counted = 9000, who = 'admin') => run({ type: 'cash.close.approve', ...closeBody(counted) }, who);
  const pay = () => { const c = state.checks[0]!, cash = state.cash_sessions.at(-1)!; const who = cash.owner_id === actor('noche').user.id ? 'noche' : 'caja'; const r = run({ type: 'collection.authorize', check_id: c.id, expected_version: c.version, cash_session_id: cash.id, method: 'cash', amount_minor: c.total_minor }, who); run({ type: 'payment.confirm', authorization_id: r.entity_id, received_minor: c.total_minor }, who); };
  const handover = () => { const r = run({ type: 'handover.begin', cash_session_id: state.cash_sessions[0]!.id, expected_version: state.cash_sessions[0]!.version, incoming_user_id: actor('noche').user.id }, 'caja'); const x = state.handovers[0]!; run({ type: 'handover.count', handover_id: r.entity_id, expected_version: x.version, counted_cash_minor: state.cash_sessions[0]!.expected_minor, stock_counts: counts() }, 'caja'); run({ type: 'handover.accept', handover_id: r.entity_id, expected_version: state.handovers[0]!.version }, 'noche'); };
  return { run, actor, cash, table, quote, accept, order, prep, claim, deliver, priority, counts, closeBody, final, approve, pay, handover, setNow: (v: string) => { now = v; }, get state() { return state; } };
}
describe('014 production coordination', () => {
  it('assigns stable sequence and waiter to staff and ticket', () => { const t = h(); t.order(); t.order(6); expect(t.state.orders.map(o => (o as any).service_sequence)).toEqual([1, 2]); expect(t.state.visits[0]).toMatchObject({ responsible_waiter_id: t.actor('mozo').user.id }); expect(t.state.print_jobs[0]).toMatchObject({ table_label: 'Mesa 01', service_sequence: 1, responsible_name: t.actor('mozo').user.name, kind: 'order' }); });
  it('audits urgency with separate aviso and leaves original ticket and money intact', () => { const t = h(); t.order(); const original = structuredClone(t.state.print_jobs[0]), check = structuredClone(t.state.checks[0]); t.priority(); expect(t.state.orders[0]).toMatchObject({ priority: 'urgent', production_version: 2 }); expect(t.state.print_jobs[0]).toEqual(original); expect(t.state.print_jobs[1]).toMatchObject({ kind: 'priority' }); expect(t.state.checks[0]).toEqual(check); });
  it.each(['cocina', 'caja'])('does not permit %s to choose urgency', who => { const t = h(); t.order(); expect(() => t.priority(who)).toThrow('perfil'); });
  it('requires reason for urgency and leaves state intact', () => { const t = h(); t.order(); const before = structuredClone(t.state); expect(() => t.priority('mozo', 'x')).toThrow('motivo'); expect(t.state).toEqual(before); });
  it('cannot change urgency on stale production version', () => { const t = h(); t.order(); t.priority(); expect(() => t.run({ type: 'order.priority', order_id: t.state.orders[0]!.id, expected_version: 1, priority: 'normal', reason: 'Volver a normal' })).toThrow('cambió'); });
  it('does not claim unprepared kitchen food', () => { const t = h(); t.order(); expect(() => t.claim()).toThrow('lista'); });
  it('prevents another waiter delivery of a claimed ready line', () => { const t = h(); t.order(); t.prep(); t.claim(); const before = structuredClone(t.state); expect(() => t.deliver('apoyo')).toThrow('retir'); expect(t.state).toEqual(before); t.deliver(); expect(t.state.orders[0]!.lines[0]).toMatchObject({ fulfilled_quantity: 1, dispatch_claim: null }); });
  it('explicit owner release allows another waiter to claim', () => { const t = h(); t.order(); t.prep(); t.claim(); expect(() => t.claim('apoyo', 'release')).toThrow('propietario'); t.claim('mozo', 'release'); t.claim('apoyo'); t.deliver('apoyo'); expect(t.state.orders[0]!.lines[0].fulfilled_quantity).toBe(1); });
  it('does not let kitchen claim floor pickup', () => { const t = h(); t.order(); t.prep(); expect(() => t.claim('cocina')).toThrow('perfil'); });
  it('staff can record explicit confirmation from paper-only kitchen without delivering', () => { const t = h(); t.order(); t.run({ type: 'line.ready.confirm', line_id: t.state.orders[0]!.lines[0]!.id, expected_version: 1, quantity: 1, reason: 'Cocinero confirmó un ceviche listo' }); expect(t.state.orders[0]!.lines[0]).toMatchObject({ prepared_quantity: 1, fulfilled_quantity: 0 }); expect(t.state.audit.at(-1)).toMatchObject({ action: 'line.ready.confirm', actor_id: t.actor('mozo').user.id, reason: 'Cocinero confirmó un ceviche listo' }); });
  it('paper confirmation requires reason and does not apply to direct beverages', () => { const t = h(); t.cash(); t.order(3); expect(() => t.run({ type: 'line.ready.confirm', line_id: t.state.orders[0]!.lines[0]!.id, expected_version: 1, quantity: 1, reason: 'Bebida ya preparada' })).toThrow('directamente'); });
  it('waiter cannot steal assignment; admin reassignment retains historical ticket', () => { const t = h(); t.order(); const original = structuredClone(t.state.print_jobs[0]); const command = { type: 'table.assign', visit_id: t.state.visits[0]!.id, expected_version: t.state.visits[0]!.version, waiter_id: t.actor('apoyo').user.id, reason: 'Relevo de salón' }; expect(() => t.run(command, 'apoyo')).toThrow('Administración'); t.run(command, 'admin'); expect(t.state.visits[0]).toMatchObject({ responsible_waiter_id: t.actor('apoyo').user.id }); expect(t.state.print_jobs[0]).toEqual(original); });
});
describe('014 night service and operational closure', () => {
  it('night rejects kitchen quotes and accepts all three beverage classes', () => { const t = h(); t.cash('nocturno', 'noche'); expect(() => t.quote(0)).toThrow('nocturno'); for (const p of [3, 4, 5]) t.order(p); expect(t.state.orders).toHaveLength(3); });
  it('rejects daytime quote after handover enters night without consuming it', () => { const t = h(); t.cash(); const q = t.quote(0); t.handover(); const before = structuredClone(t.state); expect(() => t.accept(q)).toThrow('nocturno'); expect(t.state).toEqual(before); });
  it('night custody relief does not silently reopen full-service menu', () => { const t = h(); t.cash('nocturno'); t.handover(); expect(t.state.cash_sessions.at(-1)!.shift_label).toBe('nocturno'); expect(() => t.quote(0)).toThrow('nocturno'); });
  it('projects only safe service mode without revealing financial approvals to waiter', () => { const t = h(); t.cash('nocturno', 'noche', 10000); t.approve(); const s = projectSnapshot(t.state, t.actor('mozo')); expect(s).toMatchObject({ service_mode: 'beverages_only', cash_close_approvals: [] }); expect((s as any).available_product_ids).toHaveLength(3); });
  it('keeps day ID across midnight and can fulfill prior food at night', () => { const t = h(); t.cash(); t.order(); t.handover(); const day = t.state.business_day.id; t.setNow('2026-10-04T06:30:00Z'); t.prep(); t.deliver(); expect(t.state.business_day.id).toBe(day); });
  it('closes balanced night operationally while fiscal state stays provisional', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.deliver(); t.pay(); t.final(); expect(t.state.day_closes[0]).toMatchObject({ operational_status: 'reconciled', close_mode: 'operational_final', state: 'provisionally_closed' }); expect(t.state.cash_sessions[0]!.state).toBe('closed'); });
  it('does not final-close a diurnal shift', () => { const t = h(); t.cash(); expect(() => t.final()).toThrow('nocturn'); });
  it('does not final-close unpaid checks', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.deliver(); expect(() => t.final()).toThrow('saldo'); expect(t.state.cash_sessions[0]!.state).toBe('open'); });
  it('does not final-close paid but undelivered orders', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.pay(); expect(() => t.final()).toThrow('entregar'); });
  it('does not resolve unknown payment merely by closing', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.deliver(); const a = t.run({ type: 'collection.authorize', check_id: t.state.checks[0]!.id, expected_version: t.state.checks[0]!.version, cash_session_id: t.state.cash_sessions[0]!.id, method: 'yape', amount_minor: 1000 }, 'noche'); t.run({ type: 'payment.unknown', authorization_id: a.entity_id, reason: 'Respuesta de comercio incierta' }, 'noche'); const before = structuredClone(t.state); expect(() => t.final()).toThrow('inciertos'); expect(t.state).toEqual(before); });
  it('does not final-close an unused authorization', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.run({ type: 'collection.authorize', check_id: t.state.checks[0]!.id, expected_version: t.state.checks[0]!.version, cash_session_id: t.state.cash_sessions[0]!.id, method: 'cash', amount_minor: 1000 }, 'noche'); expect(() => t.final()).toThrow('autorizaciones'); });
  it('requires inventory reconciliation before final closure', () => { const t = h(); t.cash('nocturno', 'noche'); const c = t.closeBody(); c.stock_counts[0]!.counted_quantity--; expect(() => t.run({ type: 'day.close', mode: 'operational_final', ...c }, 'noche')).toThrow('inventario'); });
  it('does not final-close pending inventory review', () => { const t = h(); t.cash('nocturno', 'noche'); t.run({ type: 'inventory.count', reason: 'Conteo pendiente físico', lines: [{ stock_item_id: t.state.stock[0]!.id, expected_version: 1, counted_quantity: 48 }] }, 'noche'); expect(() => t.final()).toThrow('conteo'); });
  it('difference of cash needs independent sealed approval', () => { const t = h(); t.cash('nocturno', 'noche', 10000); expect(() => t.final(9000)).toThrow('aproba'); const approval = t.approve().entity_id; t.final(9000, approval); expect(t.state.day_closes[0]).toMatchObject({ operational_status: 'reconciled', cash_difference_minor: -1000, cash_approval_id: approval }); });
  it('cash movement invalidates previous sealed approval', () => { const t = h(); t.cash('nocturno', 'noche', 10000); const a = t.approve().entity_id; t.run({ type: 'cash.move', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: t.state.cash_sessions[0]!.version, kind: 'paid_in', amount_minor: 1, reason: 'Entrada externa registrada' }, 'noche'); expect(() => t.final(9000, a)).toThrow('cambió'); expect(t.state.cash_sessions[0]!.state).toBe('open'); });
  it('cannot use sealed approval for different count', () => { const t = h(); t.cash('nocturno', 'noche', 10000); const a = t.approve().entity_id; expect(() => t.final(8900, a)).toThrow('conteo'); });
  it('cannot approve own cash variance', () => { const t = h(); t.cash('nocturno', 'admin', 10000); expect(() => t.approve(9000, 'admin')).toThrow('distint'); });
  it('provisional records unresolved service without claiming final', () => { const t = h(); t.cash('nocturno', 'noche'); t.order(3); t.run({ type: 'day.close', ...t.closeBody() }, 'noche'); expect(t.state.day_closes[0]).toMatchObject({ operational_status: 'pending', close_mode: 'provisional' }); });
  it('cannot downgrade a signed operational final to a new provisional revision', () => { const t = h(); t.cash('nocturno', 'noche'); t.final(); const before = structuredClone(t.state); expect(() => t.run({ type: 'day.close', ...t.closeBody() }, 'noche')).toThrow('firmado'); expect(t.state).toEqual(before); });
  it('does not receive beverage count below already reserved stock', () => { const t = h(); t.cash(); t.order(3); const r = t.run({ type: 'handover.begin', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: t.state.cash_sessions[0]!.version, incoming_user_id: t.actor('noche').user.id }, 'caja'); const counts = t.counts(); counts[0]!.counted_quantity = 0; t.run({ type: 'handover.count', handover_id: r.entity_id, expected_version: 1, counted_cash_minor: 0, stock_counts: counts }, 'caja'); t.run({ type: 'handover.approve', handover_id: r.entity_id, expected_version: 2, reason: 'Faltante observado no borra reservas' }, 'admin'); const before = structuredClone(t.state); expect(() => t.run({ type: 'handover.accept', handover_id: r.entity_id, expected_version: t.state.handovers[0]!.version }, 'noche')).toThrow('reservadas'); expect(t.state).toEqual(before); });
});


describe('014 failed custody transfer recovery', () => {
  function declared() { const t = h(); t.cash(); t.order(3); const b = t.run({ type: 'handover.begin', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: t.state.cash_sessions[0]!.version, incoming_user_id: t.actor('noche').user.id }, 'caja'); const counts = t.counts(); counts[0]!.counted_quantity = 0; t.run({ type: 'handover.count', handover_id: b.entity_id, expected_version: 1, counted_cash_minor: 0, stock_counts: counts }, 'caja'); return t; }
  const cancel = (t: ReturnType<typeof h>, who = 'admin', expected = t.state.handovers[0]!.version) => t.run({ type: 'handover.cancel', handover_id: t.state.handovers[0]!.id, expected_version: expected, reason: 'Concilia reserva antes de nuevo corte' }, who);
  it('preserves sealed observation and same owner without monetary or stock effects', () => { const t = declared(), before = structuredClone(t.state); cancel(t); expect(t.state.handovers[0]).toMatchObject({ state: 'cancelled', counted_cash_minor: 0, stock_lines: before.handovers[0]!.stock_lines, cancelled_by: t.actor('admin').user.id }); expect(t.state.cash_sessions).toHaveLength(1); expect(t.state.cash_sessions[0]).toMatchObject({ state: 'open', owner_id: t.actor('caja').user.id, shift_label: 'diurno', expected_minor: 0 }); expect(t.state.stock).toEqual(before.stock); expect(t.state.stock_movements).toEqual(before.stock_movements); expect(t.state.payments).toEqual(before.payments); });
  it('can reconcile outgoing pending beverages and restart without deleting cancelled count', () => { const t = declared(); cancel(t); t.run({ type: 'order.line.void', line_id: t.state.orders[0]!.lines[0]!.id, expected_version: t.state.visits[0]!.version, quantity: 1, reason: 'Cliente cancela unidad no entregada', restore_stock: false }, 'admin'); const b = t.run({ type: 'handover.begin', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: t.state.cash_sessions[0]!.version, incoming_user_id: t.actor('noche').user.id }, 'caja'); t.run({ type: 'handover.count', handover_id: b.entity_id, expected_version: 1, counted_cash_minor: 0, stock_counts: t.counts() }, 'caja'); t.run({ type: 'handover.accept', handover_id: b.entity_id, expected_version: 2 }, 'noche'); expect(t.state.handovers.map(x => x.state)).toEqual(['cancelled', 'accepted']); });
  it('rejects stale cancellation and ordinary cashier without any mutation', () => { const t = declared(), before = structuredClone(t.state); expect(() => cancel(t, 'caja')).toThrow('perfil'); expect(() => cancel(t, 'admin', 1)).toThrow('cambió'); expect(t.state).toEqual(before); });
  it('requires independent administrator and cannot undo accepted custody', () => { const t = h(); t.cash('diurno', 'admin'); const b = t.run({ type: 'handover.begin', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: 1, incoming_user_id: t.actor('noche').user.id }, 'admin'); expect(() => cancel(t)).toThrow('distinta'); t.run({ type: 'handover.count', handover_id: b.entity_id, expected_version: 1, counted_cash_minor: 0, stock_counts: t.counts() }, 'admin'); t.run({ type: 'handover.accept', handover_id: b.entity_id, expected_version: 2 }, 'noche'); expect(() => cancel(t)).toThrow('distinta'); });
});


describe('014 cancellation terminal states', () => {
  it.each(['prepared', 'disputed'])('can cancel %s without receiving successor custody', stage => { const t = h(); t.cash(); const b = t.run({ type: 'handover.begin', cash_session_id: t.state.cash_sessions[0]!.id, expected_version: t.state.cash_sessions[0]!.version, incoming_user_id: t.actor('noche').user.id }, 'caja'); if (stage === 'disputed') { t.run({ type: 'handover.count', handover_id: b.entity_id, expected_version: 1, counted_cash_minor: 0, stock_counts: t.counts() }, 'caja'); t.run({ type: 'handover.reject', handover_id: b.entity_id, expected_version: 2, reason: 'Observación de conteo saliente' }, 'noche'); } t.run({ type: 'handover.cancel', handover_id: b.entity_id, expected_version: t.state.handovers[0]!.version, reason: 'Revisión administrativa del corte' }, 'admin'); expect(t.state.handovers[0]).toMatchObject({ state: 'cancelled', successor_cash_session_id: null }); expect(t.state.cash_sessions[0]!.state).toBe('open'); });
  it('independent admin cannot cancel an already accepted transfer', () => { const t = h(); t.cash(); t.handover(); const before = structuredClone(t.state); expect(() => t.run({ type: 'handover.cancel', handover_id: t.state.handovers[0]!.id, expected_version: t.state.handovers[0]!.version, reason: 'No deshacer custodia recibida' }, 'admin')).toThrow('todavía no recibido'); expect(t.state).toEqual(before); });
});
